import { useEffect, useState } from 'react';
import { MapPin, MessageCircle, Send, Sparkles, UserRound, X } from 'lucide-react';
import type { MomentAuthor, MomentComment, MomentPost } from '@soren/shared';
import { api } from '../../api';

const authorName=(author:MomentAuthor)=>author==='soren'?'Soren':'我';
const when=(value:string)=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));

export function MomentsView({onUnreadChange}:{onUnreadChange:(count:number)=>void}){
  const[posts,setPosts]=useState<MomentPost[]>([]),[loading,setLoading]=useState(true),[content,setContent]=useState(''),[author,setAuthor]=useState<MomentAuthor>('user'),[location,setLocation]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),[reply,setReply]=useState<{momentId:string;comment:MomentComment|null}|null>(null),[comment,setComment]=useState('');
  const load=async()=>{setLoading(true);try{const data=await api<{moments:MomentPost[];unreadCount:number}>('/api/moments');setPosts(data.moments);onUnreadChange(data.unreadCount);if(data.unreadCount){const read=await api<{unreadCount:number}>('/api/moments/read',{method:'POST',body:JSON.stringify({ids:data.moments.filter(item=>!item.readAt).map(item=>item.id)})});onUnreadChange(read.unreadCount);setPosts(items=>items.map(item=>({...item,readAt:item.readAt||new Date().toISOString()})));}setError('');}catch(error:any){setError(error?.message||'Moments 暂时无法打开');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const publish=async()=>{if(!content.trim()||sending)return;setSending(true);try{const data=await api<{moment:MomentPost;unreadCount:number}>('/api/moments',{method:'POST',body:JSON.stringify({author,content,location})});setPosts(items=>[data.moment,...items]);setContent('');setLocation('');if(data.unreadCount){await api('/api/moments/read',{method:'POST',body:JSON.stringify({ids:[data.moment.id]})});}onUnreadChange(0);setError('');}catch(error:any){setError(error?.message||'没有发布成功');}finally{setSending(false);}};
  const sendComment=async()=>{if(!reply||!comment.trim())return;try{const data=await api<{comment:MomentComment}>(`/api/moments/${reply.momentId}/comments`,{method:'POST',body:JSON.stringify({author:'user',content:comment,replyToCommentId:reply.comment?.id||null})});setPosts(items=>items.map(item=>item.id===reply.momentId?{...item,comments:[...item.comments,data.comment]}:item));setReply(null);setComment('');setError('');}catch(error:any){setError(error?.message||'评论没有发出去');}};
  return <section className="moments-view"><header className="moments-head"><div><span>PRIVATE FEED</span><h1>Moments</h1><p>你和 Soren 留下的片刻，不催促回应，也不会发送系统通知。</p></div></header><div className="moments-column"><article className="moment-composer"><div className="author-switch"><button className={author==='user'?'active':''} onClick={()=>setAuthor('user')}><UserRound size={15}/>我</button><button className={author==='soren'?'active':''} onClick={()=>setAuthor('soren')}><Sparkles size={15}/>Soren</button></div><textarea value={content} onChange={event=>setContent(event.target.value)} placeholder={author==='soren'?'替 Soren 手动留下一条动态……':'这一刻，想留下什么？'} maxLength={10000}/><div className="moment-compose-foot"><label><MapPin size={14}/><input value={location} onChange={event=>setLocation(event.target.value)} placeholder="地点（可选）" maxLength={160}/></label><button onClick={publish} disabled={!content.trim()||sending}><Send size={15}/>{sending?'正在发布':'发布'}</button></div>{author==='soren'&&<small className="controlled-note">Soren 动态目前由你手动触发；以后主动系统也会走同一条安全入口。</small>}</article>{error&&<div className="moment-error">{error}<button onClick={()=>setError('')}>×</button></div>}{loading?<div className="moments-empty">正在打开这些片刻……</div>:posts.length===0?<div className="moments-empty"><Sparkles/><h2>这里还很安静</h2><p>第一条动态可以很简单，比如今天看到的一束光。</p></div>:posts.map(post=><article className={`moment-card ${post.author}`} key={post.id}><div className="moment-avatar">{post.author==='soren'?'S':<UserRound size={20}/>}</div><div className="moment-main"><div className="moment-meta"><strong>{authorName(post.author)}</strong><time>{when(post.createdAt)}</time></div><p className="moment-text">{post.content}</p>{post.location&&<span className="moment-location"><MapPin size={13}/>{post.location}</span>}<button className="comment-action" onClick={()=>{setReply({momentId:post.id,comment:null});setComment('');}}><MessageCircle size={14}/>评论</button>{post.comments.length>0&&<div className="comment-list">{post.comments.map(item=>{const parent=item.replyToCommentId?post.comments.find(candidate=>candidate.id===item.replyToCommentId):null;return <button key={item.id} onClick={()=>{setReply({momentId:post.id,comment:item});setComment('');}}><strong>{authorName(item.author)}</strong>{parent&&<span>回复 {authorName(parent.author)}</span>}<p>{item.content}</p></button>;})}</div>}</div></article>)}</div>{reply&&<div className="comment-dock"><div><span>{reply.comment?`回复 ${authorName(reply.comment.author)}`:'写评论'}</span><button onClick={()=>setReply(null)}><X size={15}/></button></div><textarea autoFocus value={comment} onChange={event=>setComment(event.target.value)} placeholder="说点什么……" onKeyDown={event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey))sendComment();}}/><button onClick={sendComment} disabled={!comment.trim()}><Send size={15}/>发送</button></div>}</section>;
}
