import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './home.css';
import './memory.css';
import './moments.css';
import './cyberdaddy.css';
import './mobile.css';
import { registerServiceWorker } from './push-client';
void registerServiceWorker();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
