import { api } from './api';
import { PushConnectionError,runPushConnection,type PushProgress,type PushStage } from './push-flow';

export type PushUiStatus={browserSupported:boolean;permission:string;serverConfigured:boolean;publicKey:string;subscribed:boolean;subscription?:{id:string;deviceLabel:string}|null;activeDevices:number;};
const storageKey='soren.push.subscriptionId';
export const pushSupported=()=>typeof window!=='undefined'&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;
export const currentNotificationPermission=()=>pushSupported()?Notification.permission:'unsupported';
const readyTimeout=(promise:Promise<ServiceWorkerRegistration>)=>Promise.race([promise,new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('Service Worker ready timeout')),15_000))]);
export const registerServiceWorker=async()=>{if(!pushSupported())return null;await navigator.serviceWorker.register('/sw.js',{scope:'/'});return readyTimeout(navigator.serviceWorker.ready);};
const applicationKey=(value:string)=>{const padded=value+'='.repeat((4-value.length%4)%4),raw=atob(padded.replace(/-/g,'+').replace(/_/g,'/')),key=Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));if(key.length!==65||key[0]!==4)throw new PushConnectionError('push_subscription_created','Soren Core 返回的 VAPID public key 无效');return key;};
const reportProgress=(progress:PushProgress)=>{const payload={...progress,origin:window.location.origin,standalone:window.matchMedia('(display-mode: standalone)').matches};void api('/api/push/diagnostics',{method:'POST',body:JSON.stringify(payload)}).catch(()=>{});};
export async function pushStatus():Promise<PushUiStatus>{const supported=pushSupported(),permission=currentNotificationPermission(),subscriptionId=localStorage.getItem(storageKey)||'',query=new URLSearchParams({supported:supported?'1':'0',permission,subscriptionId}),status=await api<PushUiStatus>(`/api/push/status?${query}`);if(!status.subscribed&&subscriptionId)localStorage.removeItem(storageKey);return{...status,permission};}
export async function subscribeThisDevice(deviceLabel='此设备',onProgress?:(progress:PushProgress)=>void){const status=await pushStatus();if(!status.browserSupported)throw new PushConnectionError('permission_request','当前浏览器不支持 Web Push');if(!status.serverConfigured)throw new PushConnectionError('push_subscription_created','Soren Core 尚未配置 Web Push');if(currentNotificationPermission()==='denied')throw new PushConnectionError('permission_request','通知权限已被浏览器拒绝，请在站点设置中修改');const progress=(item:PushProgress)=>{reportProgress(item);onProgress?.(item);};await runPushConnection({permission:currentNotificationPermission(),requestPermission:()=>Notification.requestPermission(),serviceWorkerReady:async()=>{const registration=await registerServiceWorker();if(!registration?.active)throw new Error('Service Worker is not active');return registration;},applicationServerKey:applicationKey(status.publicKey),postSubscription:async browserSubscription=>{const result=await api<{subscription:{id:string}}>(`/api/push/subscribe`,{method:'POST',body:JSON.stringify({...browserSubscription.toJSON(),deviceLabel})});localStorage.setItem(storageKey,result.subscription.id);},onProgress:progress});return pushStatus();}
export async function unsubscribeThisDevice(){const id=localStorage.getItem(storageKey),registration=pushSupported()?await navigator.serviceWorker.ready:null,browserSubscription=registration?await registration.pushManager.getSubscription():null;if(browserSubscription)await browserSubscription.unsubscribe();if(id)await api(`/api/push/subscriptions/${encodeURIComponent(id)}`,{method:'DELETE'}).catch(()=>{});localStorage.removeItem(storageKey);return pushStatus();}
export const sendTestPush=()=>api('/api/push/test',{method:'POST'});
export type {PushProgress,PushStage};
