import { api } from './api';

export type PushUiStatus={browserSupported:boolean;permission:string;serverConfigured:boolean;publicKey:string;subscribed:boolean;subscription?:{id:string;deviceLabel:string}|null;activeDevices:number;};
const storageKey='soren.push.subscriptionId';
export const pushSupported=()=>typeof window!=='undefined'&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;
export const registerServiceWorker=async()=>pushSupported()?navigator.serviceWorker.register('/sw.js',{scope:'/'}):null;
const applicationKey=(value:string)=>{const padded=value+'='.repeat((4-value.length%4)%4),raw=atob(padded.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));};
export async function pushStatus():Promise<PushUiStatus>{const supported=pushSupported(),permission=supported?Notification.permission:'unsupported',subscriptionId=localStorage.getItem(storageKey)||'',query=new URLSearchParams({supported:supported?'1':'0',permission,subscriptionId}),status=await api<PushUiStatus>(`/api/push/status?${query}`);if(!status.subscribed&&subscriptionId)localStorage.removeItem(storageKey);return status;}
export async function subscribeThisDevice(deviceLabel='此设备'){const status=await pushStatus();if(!status.browserSupported)throw new Error('当前浏览器不支持 Web Push');if(!status.serverConfigured)throw new Error('Soren Core 尚未配置 Web Push');if(Notification.permission==='denied')throw new Error('通知权限已被浏览器拒绝，请在浏览器设置中修改');const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission!=='granted')throw new Error('没有获得通知权限');const registration=await registerServiceWorker();if(!registration)throw new Error('Service Worker 不可用');let browserSubscription=await registration.pushManager.getSubscription();if(!browserSubscription)browserSubscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationKey(status.publicKey)});const result=await api<{subscription:{id:string}}>(`/api/push/subscribe`,{method:'POST',body:JSON.stringify({...browserSubscription.toJSON(),deviceLabel})});localStorage.setItem(storageKey,result.subscription.id);return pushStatus();}
export async function unsubscribeThisDevice(){const id=localStorage.getItem(storageKey),registration=pushSupported()?await navigator.serviceWorker.ready:null,browserSubscription=registration?await registration.pushManager.getSubscription():null;if(browserSubscription)await browserSubscription.unsubscribe();if(id)await api(`/api/push/subscriptions/${encodeURIComponent(id)}`,{method:'DELETE'}).catch(()=>{});localStorage.removeItem(storageKey);return pushStatus();}
export const sendTestPush=()=>api('/api/push/test',{method:'POST'});
