import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Clock3, Cloud, Folder, MessageCircle, RefreshCw, Sparkles } from 'lucide-react';
import type { HomeSnapshot, HomeTodayItem } from '@soren/shared';
import { api } from '../../api';

export function HomeView({onReply,onOpen,onMoments,onUnreadChange}:{onReply:(content:string)=>void;onOpen:(item:HomeTodayItem)=>void;onMoments:()=>void;onUnreadChange:(count:number)=>void}){
  const[data,setData]=useState<HomeSnapshot|null>(null),[failed,setFailed]=useState(false),[refreshing,setRefreshing]=useState(false);
  const load=async()=>{setRefreshing(true);try{const snapshot=await api<HomeSnapshot>('/api/home');setData(snapshot);onUnreadChange(snapshot.moments.unreadCount);setFailed(false);}catch{setFailed(true);}finally{setRefreshing(false);}};
  useEffect(()=>{load();},[]);
  const date=useMemo(()=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date()),[]);
  const itemIcon=(type:HomeTodayItem['type'])=>type==='chat'?<MessageCircle/>:type==='workspace'?<Folder/>:<Clock3/>;
  return <section className="home-view"><div className="home-date"><span>{new Date().getFullYear()}</span><h1>{date}</h1></div><div className="home-grid"><article className="home-note"><div className="card-kicker"><Sparkles size={15}/>Soren 留给你</div><p>{data?.note.content||'我在这里。'}</p><button onClick={()=>data&&onReply(data.note.content)} disabled={!data}>在 Chat 里回应<ArrowRight size={15}/></button></article><article className="weather-card"><div className="card-kicker"><Cloud size={15}/>{data?.weather.location?[data.weather.location.name,data.weather.location.admin1].filter(Boolean).join(' · '):'天气'}</div>{data?.weather.status==='ready'?<><strong>{Math.round(data.weather.temperature||0)}°</strong><h2>{data.weather.label}</h2><p>体感 {Math.round(data.weather.apparentTemperature||0)}° · {Math.round(data.weather.minimum||0)}°–{Math.round(data.weather.maximum||0)}° · 降水 {Math.round(data.weather.precipitationProbability||0)}%</p></>:<><h2>{data?.weather.label||'天气正在抵达'}</h2><p>{data?.weather.status==='unconfigured'?'在 Settings 里选择常驻城市。':'天气暂时不可用，不影响今天的其他内容。'}</p></>}<button className="quiet-icon" onClick={load} disabled={refreshing} title="刷新天气"><RefreshCw size={15}/></button></article><article className="today-card"><div className="card-kicker">Today</div>{data?.today.length?<div className="today-list">{data.today.map(item=><button key={`${item.type}-${item.id}`} onClick={()=>onOpen(item)}>{itemIcon(item.type)}<span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowRight size={14}/></button>)}</div>:<p className="home-muted">今天还很安静。想开始时，我就在 Chat 里。</p>}</article><button className="moments-entry" onClick={onMoments}><div><div className="card-kicker">Moments {Boolean(data?.moments.unreadCount)&&<i className="unread-dot"/>}</div><h2>我们的动态会留在这里</h2><p>{data?.moments.unreadCount?`有 ${data.moments.unreadCount} 条新动态，等你慢慢发现。`:'一些不需要立即回应的片刻。'}</p></div><span>打开 Moments <ArrowRight size={14}/></span></button></div>{failed&&<div className="home-fallback">Home 暂时没有取到最新内容，Chat 和 Workspace 仍可正常使用。<button onClick={load}>重试</button></div>}</section>;
}
