import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Check, Moon, Pause, Play, Plus, ShieldCheck, X } from 'lucide-react';
import type { CyberDaddySnapshot, CyberDaddyIntensity } from '@soren/shared';
import { api } from '../../api';

const intensityNames:Record<CyberDaddyIntensity,string>={gentle:'Gentle',normal:'Normal',daddy:'Daddy'};
const actionNames:Record<string,string>={REMIND:'提醒',FOLLOW_UP:'继续跟进',REDUCE_TASK:'缩小任务',POSTPONE:'推迟',CHECK_IN:'关心状态',NO_ACTION:'不打扰'};
const dateTime=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'不设截止时间';

export function CyberDaddyPanel(){
  const[snapshot,setSnapshot]=useState<CyberDaddySnapshot|null>(null),[description,setDescription]=useState(''),[domainId,setDomainId]=useState('study'),[recurrence,setRecurrence]=useState<'none'|'daily'>('none'),[targetAt,setTargetAt]=useState(''),[dailyTime,setDailyTime]=useState('22:30'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=()=>api<CyberDaddySnapshot>('/api/cyberdaddy').then(setSnapshot).catch((reason)=>setError(reason.message));
  useEffect(()=>{void load();},[]);
  const active=useMemo(()=>snapshot?.commitments.filter(item=>item.status==='active')||[],[snapshot]);
  async function config(input:Record<string,unknown>){setBusy(true);setError('');try{setSnapshot(await api('/api/cyberdaddy',{method:'PATCH',body:JSON.stringify(input)}));}catch(reason:any){setError(reason.message);}finally{setBusy(false);}}
  async function domain(id:string,input:Record<string,unknown>){setBusy(true);setError('');try{const result=await api<{snapshot:CyberDaddySnapshot}>(`/api/cyberdaddy/domains/${id}`,{method:'PATCH',body:JSON.stringify(input)});setSnapshot(result.snapshot);}catch(reason:any){setError(reason.message);}finally{setBusy(false);}}
  async function create(event:FormEvent){event.preventDefault();if(!description.trim()||(recurrence==='none'&&!targetAt))return;setBusy(true);setError('');try{const result=await api<{snapshot:CyberDaddySnapshot}>('/api/commitments',{method:'POST',body:JSON.stringify({domainId,description,recurrence,recurrenceTime:recurrence==='daily'?dailyTime:null,targetAt:recurrence==='none'?new Date(targetAt).toISOString():null})});setSnapshot(result.snapshot);setDescription('');setTargetAt('');}catch(reason:any){setError(reason.message);}finally{setBusy(false);}}
  async function update(id:string,status:'completed'|'cancelled'){setBusy(true);setError('');try{const result=await api<{snapshot:CyberDaddySnapshot}>(`/api/commitments/${id}`,{method:'PATCH',body:JSON.stringify({status})});setSnapshot(result.snapshot);}catch(reason:any){setError(reason.message);}finally{setBusy(false);}}
  if(!snapshot)return <section className="cyber-card"><p>{error||'正在读取 Soren 的督促设置…'}</p></section>;
  return <section className="cyber-stack">
    <article className="cyber-card cyber-overview"><div><span className="eyebrow"><ShieldCheck/> SOREN SUPERVISION</span><h2>答应自己的事，我替你记着。</h2><p>只有你启用的领域才会跟进；安静时间和暂停状态始终优先。</p></div><div className="cyber-master"><button className={snapshot.enabled?'switch active':'switch'} disabled={busy} onClick={()=>config({enabled:!snapshot.enabled})}><i/><span>{snapshot.enabled?'已开启':'未开启'}</span></button><button className="quiet-button" disabled={busy||!snapshot.enabled} onClick={()=>config({paused:!snapshot.paused})}>{snapshot.paused?<Play/>:<Pause/>}{snapshot.paused?'恢复':'暂停'}</button></div></article>
    <article className="cyber-card"><div className="cyber-title"><div><h3>监督范围</h3><p>每个领域独立选择强度。Gentle 只提醒一次，Daddy 会有限度地持续确认。</p></div><div className="quiet-hours"><Moon/><input type="time" value={snapshot.quietStart} onChange={event=>config({quietStart:event.target.value})}/><span>—</span><input type="time" value={snapshot.quietEnd} onChange={event=>config({quietEnd:event.target.value})}/></div></div><div className="domain-grid">{snapshot.domains.map(item=><div className={item.enabled?'domain-item enabled':'domain-item'} key={item.id}><button className={item.enabled?'mini-switch active':'mini-switch'} disabled={busy} onClick={()=>domain(item.id,{enabled:!item.enabled})}><i/></button><strong>{item.name}</strong><select value={item.intensity} disabled={busy||!item.enabled} onChange={event=>domain(item.id,{intensity:event.target.value})}>{Object.entries(intensityNames).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>)}</div></article>
    <article className="cyber-card"><div className="cyber-title"><div><h3>我的承诺</h3><p>到时间后，Soren 会结合最近状态决定提醒、缩小任务，或者先不追进度。</p></div><span className={snapshot.inQuietHours?'pulse-status quiet':'pulse-status'}>{snapshot.inQuietHours?'安静时间中':snapshot.lastOutcome}</span></div><form className="commitment-form" onSubmit={create}><select value={domainId} onChange={event=>setDomainId(event.target.value)}>{snapshot.domains.map(item=><option key={item.id} value={item.id}>{item.name}{item.enabled?'':'（未启用）'}</option>)}</select><input value={description} onChange={event=>setDescription(event.target.value)} placeholder="例如：每天 12 点前睡觉"/><select value={recurrence} onChange={event=>setRecurrence(event.target.value as 'none'|'daily')}><option value="none">仅一次</option><option value="daily">每天</option></select>{recurrence==='daily'?<input aria-label="每天跟进时间" type="time" value={dailyTime} onChange={event=>setDailyTime(event.target.value)}/>:<input aria-label="截止时间" type="datetime-local" value={targetAt} onChange={event=>setTargetAt(event.target.value)}/>}<button className="primary" disabled={busy||!description.trim()||(recurrence==='none'&&!targetAt)}><Plus/>记下来</button></form><div className="commitment-list">{active.length?active.map(item=>{const domainItem=snapshot.domains.find(domain=>domain.id===item.domainId);return <div key={item.id}><span className="commitment-domain">{domainItem?.name||item.domainId}</span><div><strong>{item.description}</strong><small>{item.recurrence==='daily'?`每天 ${item.recurrenceTime} 跟进`:dateTime(item.targetAt)}{item.followUpCount?` · 共跟进 ${item.followUpCount} 次`:''}</small></div><button title="完成" disabled={busy} onClick={()=>update(item.id,'completed')}><Check/></button><button title="取消" disabled={busy} onClick={()=>update(item.id,'cancelled')}><X/></button></div>}):<div className="cyber-empty">还没有进行中的承诺。</div>}</div>{error&&<p className="cyber-error">{error}</p>}</article>
    {snapshot.followUps.length>0&&<article className="cyber-card"><div className="cyber-title"><div><h3>最近跟进</h3><p>Soren 做过什么判断，会留在这里。</p></div></div><div className="followup-list">{snapshot.followUps.slice(0,6).map(item=><div key={item.id}><time>{dateTime(item.createdAt)}</time><strong>{actionNames[item.action]||item.action}</strong><p>{item.message||item.reason}</p></div>)}</div></article>}
  </section>;
}
