import { useEffect, useRef, useState } from 'react';
import Editor from '@monaco-editor/react';
import { ArrowLeft, ChevronDown, Code2, File, Folder, History, Pencil, Plus, RotateCcw, Save, Search, TerminalSquare } from 'lucide-react';
import type { WorkspaceFile, WorkspaceProject } from '@soren/shared';
import { api } from '../../api';
import { Markdown } from '../../components/Markdown';

const language=(path:string)=>path.endsWith('.html')?'html':path.endsWith('.css')?'css':path.endsWith('.js')?'javascript':path.endsWith('.json')?'json':path.endsWith('.md')?'markdown':'plaintext';

export function WorkspaceView({openProjectId,setOpenProjectId,onAsk}:{openProjectId:string|null;setOpenProjectId:(id:string|null)=>void;onAsk:(p:WorkspaceProject)=>void}){
  const[projects,setProjects]=useState<WorkspaceProject[]>([]),[project,setProject]=useState<WorkspaceProject|null>(null),[files,setFiles]=useState<WorkspaceFile[]>([]),[path,setPath]=useState(''),[content,setContent]=useState(''),[saved,setSaved]=useState(true),[tab,setTab]=useState<'code'|'preview'|'console'|'diff'|'history'>('code'),[diff,setDiff]=useState(''),[history,setHistory]=useState<any[]>([]),[logs,setLogs]=useState<string[]>([]);const saveTimer=useRef<number|undefined>(undefined);
  const loadProjects=()=>api<{projects:WorkspaceProject[]}>('/api/projects').then(data=>setProjects(data.projects));useEffect(()=>{loadProjects()},[]);
  useEffect(()=>{if(!openProjectId){setProject(null);return;}api<{project:WorkspaceProject;files:WorkspaceFile[]}>(`/api/projects/${openProjectId}`).then(data=>{setProject(data.project);setFiles(data.files);const first=data.files.find(file=>file.type==='file');if(first)openFile(first.path);});},[openProjectId]);
  useEffect(()=>{const listener=(event:MessageEvent)=>{if(event.data?.source==='soren-preview')setLogs(items=>[...items,`[${event.data.level}] ${event.data.args.join(' ')}`].slice(-200));};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener);},[]);
  const openFile=async(filePath:string)=>{const data=await api<{content:string}>(`/api/projects/${openProjectId}/file?path=${encodeURIComponent(filePath)}`);setPath(filePath);setContent(data.content);setSaved(true);setTab('code');};
  const update=(value:string|undefined)=>{const next=value||'';setContent(next);setSaved(false);clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(async()=>{await api(`/api/projects/${openProjectId}/file`,{method:'PUT',body:JSON.stringify({path,content:next})});setSaved(true);setFiles((await api<{files:WorkspaceFile[]}>(`/api/projects/${openProjectId}/files`)).files);},500);};
  const loadTab=async(next:typeof tab)=>{setTab(next);if(next==='diff')setDiff((await api<{diff:string}>(`/api/projects/${openProjectId}/diff`)).diff);if(next==='history')setHistory((await api<{history:any[]}>(`/api/projects/${openProjectId}/history`)).history);};
  const create=async()=>{const name=prompt('项目名称');if(!name)return;const type=(prompt('项目类型：web / markdown / files','web')||'web');const{project}=await api<{project:WorkspaceProject}>('/api/projects',{method:'POST',body:JSON.stringify({name,type})});await loadProjects();setOpenProjectId(project.id);};
  if(!project)return <section className="surface workspace-home"><div className="surface-head"><div><h1>Workspace</h1><p>这里展示 Soren 专属目录中的真实项目。</p></div><button className="primary" onClick={create}><Plus size={17}/>新建项目</button></div>{projects.length?<div className="project-grid">{projects.map(item=><button className="project-card" key={item.id} onClick={()=>setOpenProjectId(item.id)}><div className="project-icon"><Folder/></div><h2>{item.name}</h2><p>{item.type==='web'?'网页与小游戏':item.type==='markdown'?'Markdown 文档':'文件项目'}</p><span>{item.gitStatus==='clean'?'版本已保存':'有未保存版本'} · {new Date(item.updatedAt).toLocaleDateString('zh-CN')}</span></button>)}</div>:<div className="empty-card"><Folder/><h2>还没有项目</h2><p>新建后会在本机生成真实文件和独立版本历史。</p></div>}</section>;
  const previewPath=project.previewEntry||files.find(file=>file.path.endsWith('.html'))?.path||files.find(file=>file.path.endsWith('.md'))?.path;
  return <section className="workspace-detail"><div className="workspace-title"><button className="back" onClick={()=>setOpenProjectId(null)}><ArrowLeft size={17}/>全部项目</button><div><h1>{project.name}</h1><span>{saved?'已保存':'保存中…'}</span></div><div className="workspace-actions"><button onClick={()=>onAsk(project)}>Ask Soren</button><button className="primary" onClick={async()=>{await api(`/api/projects/${project.id}/commit`,{method:'POST',body:JSON.stringify({message:'Save version'})});loadProjects();}}><Save size={16}/>保存版本</button></div></div><div className="workbench"><aside className="file-tree"><label><Search size={14}/><input placeholder="筛选文件"/></label>{files.map(file=><button key={file.path} className={path===file.path?'active':''} disabled={file.type==='directory'} onClick={()=>file.type==='file'&&openFile(file.path)}>{file.type==='directory'?<Folder size={15}/>:<File size={15}/>}<span>{file.path}</span>{file.status&&<i/>}</button>)}</aside><div className="editor-pane"><div className="tabs">{([['code',Code2],['preview',ChevronDown],['console',TerminalSquare],['diff',Pencil],['history',History]] as const).map(([id,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>loadTab(id)}><Icon size={15}/>{id[0].toUpperCase()+id.slice(1)}</button>)}</div><div className="tab-body">{tab==='code'&&<Editor height="100%" theme="vs-light" language={language(path)} value={content} onChange={update} options={{fontSize:14,minimap:{enabled:false},wordWrap:'on',padding:{top:18},fontFamily:"'SFMono-Regular', Consolas, monospace"}}/>}{tab==='preview'&&(previewPath?.endsWith('.md')?<div className="markdown-preview"><Markdown>{previewPath===path?content:'打开 README.md 查看预览'}</Markdown></div>:previewPath?<iframe className="preview-frame" sandbox="allow-scripts" src={`/api/projects/${project.id}/preview/${encodeURI(previewPath)}?t=${Date.now()}`}/>:<div className="tab-empty">项目里还没有可预览的 HTML 或 Markdown。</div>)}{tab==='console'&&<pre className="console">{logs.join('\n')||'Preview Console · 等待页面输出'}</pre>}{tab==='diff'&&<pre className="diff">{diff||'当前没有未提交修改。'}</pre>}{tab==='history'&&<div className="history-list">{history.map(item=><article key={item.id}><div><strong>{item.message}</strong><span>{item.shortId} · {new Date(item.date).toLocaleString('zh-CN')}</span></div><button onClick={async()=>{if(confirm(`恢复到 ${item.shortId}？恢复会创建一个新版本。`)){await api(`/api/projects/${project.id}/restore`,{method:'POST',body:JSON.stringify({commit:item.id})});location.reload();}}}><RotateCcw size={14}/>恢复</button></article>)}</div>}</div></div></div></section>;
}
