import type { Commitment, CommitmentFollowUp, CommitmentRecurrence, CyberDaddyDomain, CyberDaddyIntensity, CyberDaddySnapshot } from '@soren/shared';
import type { SorenDatabase } from './db.js';
import type { EventService } from './event-service.js';
import { hasObviousHighBurden, RuleBasedCyberDaddyEvaluator, type CyberDaddyContextEvaluator } from './cyberdaddy-evaluator.js';

const nowIso=()=>new Date().toISOString();
const parse=<T>(value:unknown,fallback:T):T=>{try{return JSON.parse(String(value)) as T;}catch{return fallback;}};
const bool=(value:unknown)=>Boolean(Number(value));
const validIntensity=(value:unknown):CyberDaddyIntensity=>value==='gentle'||value==='daddy'?value:'normal';
const validTime=(value:unknown,fallback:string)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(value||''))?String(value):fallback;
const dateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const dailyTarget=(at:Date,time:string,nextIfPast:boolean)=>{const[hours,minutes]=time.split(':').map(Number),target=new Date(at);target.setHours(hours,minutes,0,0);if(nextIfPast&&target.getTime()<=at.getTime())target.setDate(target.getDate()+1);return target;};
const validRecurrence=(value:unknown):CommitmentRecurrence=>value==='daily'?'daily':'none';

const defaultDomains=[
  ['sleep','作息'],['study','学习 / IELTS'],['career','求职'],['fitness','运动'],['projects','个人项目'],['habits','生活习惯']
] as const;

export class CyberDaddyService {
  private timer:NodeJS.Timeout|null=null;
  private running=false;
  readonly dailyLimit=6;
  private readonly rules=new RuleBasedCyberDaddyEvaluator();
  constructor(private readonly db:SorenDatabase,private readonly events:EventService,private readonly clock:()=>Date=()=>new Date(),private readonly contextualEvaluator:CyberDaddyContextEvaluator|null=null){this.ensureDomains();}

  start(){if(this.timer)return;this.timer=setInterval(()=>void this.pulse(),60_000);this.timer.unref();void this.pulse();}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
  snapshot():CyberDaddySnapshot{const current=this.clock();return{enabled:this.db.setting('cyberdaddyEnabled',false),paused:this.db.setting('cyberdaddyPaused',false)||this.db.setting('proactivePaused',false),quietStart:this.db.setting('cyberdaddyQuietStart','23:00'),quietEnd:this.db.setting('cyberdaddyQuietEnd','08:00'),inQuietHours:this.isQuiet(current),running:this.running,lastPulseAt:this.db.setting<string|null>('cyberdaddyLastPulseAt',null),lastOutcome:this.db.setting('cyberdaddyLastOutcome','尚未运行'),domains:this.domains(),commitments:this.commitments(),followUps:this.followUps()};}
  updateConfig(input:Record<string,unknown>){if('enabled'in input)this.db.setSetting('cyberdaddyEnabled',Boolean(input.enabled));if('paused'in input)this.db.setSetting('cyberdaddyPaused',Boolean(input.paused));if('quietStart'in input)this.db.setSetting('cyberdaddyQuietStart',validTime(input.quietStart,'23:00'));if('quietEnd'in input)this.db.setSetting('cyberdaddyQuietEnd',validTime(input.quietEnd,'08:00'));return this.snapshot();}
  domains():CyberDaddyDomain[]{return(this.db.db.prepare('SELECT * FROM cyberdaddy_domains ORDER BY created_at').all() as any[]).map(this.mapDomain);}
  updateDomain(id:string,input:Record<string,unknown>){const current=this.domain(id);if(!current)return null;const at=nowIso(),name=String(input.name??current.name).trim().slice(0,80)||current.name,enabled='enabled'in input?Boolean(input.enabled):current.enabled,intensity=validIntensity(input.intensity??current.intensity),settings=input.settings&&typeof input.settings==='object'?input.settings:current.settings;this.db.db.prepare('UPDATE cyberdaddy_domains SET name=?,enabled=?,intensity=?,settings_json=?,updated_at=? WHERE id=?').run(name,enabled?1:0,intensity,JSON.stringify(settings),at,id);return this.domain(id);}
  commitments(status=''):Commitment[]{return(this.db.db.prepare(`SELECT * FROM commitments WHERE (?='' OR status=?) ORDER BY CASE status WHEN 'active' THEN 0 ELSE 1 END,COALESCE(target_at,created_at)`).all(status,status) as any[]).map(this.mapCommitment);}
  createCommitment(input:Record<string,unknown>){const domainId=String(input.domainId||''),domain=this.domain(domainId),description=String(input.description||'').trim(),recurrence=validRecurrence(input.recurrence),recurrenceTime=recurrence==='daily'?validTime(input.recurrenceTime,''):null;if(!domain)throw new Error('监督领域不存在');if(!description)throw new Error('承诺内容不能为空');if(recurrence==='daily'&&!recurrenceTime)throw new Error('每天重复需要选择跟进时间');if(recurrence==='none'&&!input.targetAt)throw new Error('请选择日期时间，或设为每天重复');if(input.targetAt&&!Number.isFinite(Date.parse(String(input.targetAt))))throw new Error('目标时间无效');const now=this.clock(),daily=recurrence==='daily'?dailyTarget(now,recurrenceTime!,true):null,targetAt=daily?.toISOString()||(input.targetAt?new Date(String(input.targetAt)).toISOString():null),cycleKey=daily?dateKey(daily):null,id=crypto.randomUUID(),at=now.toISOString();this.db.db.prepare(`INSERT INTO commitments (id,domain_id,description,status,target_at,created_at,updated_at,completed_at,source_conversation_id,last_followup_at,next_followup_at,followup_count,metadata_json,recurrence,recurrence_time,cycle_key,cycle_followup_count) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,domainId,description.slice(0,1000),'active',targetAt,at,at,null,input.sourceConversationId?String(input.sourceConversationId):null,null,null,0,JSON.stringify(input.metadata&&typeof input.metadata==='object'?input.metadata:{}),recurrence,recurrenceTime,cycleKey,0);const commitment=this.commitment(id)!;this.events.emit({type:'commitment.created',sourceType:'commitment',sourceId:id,title:domain.name,body:commitment.description,payload:{domainId,targetAt,recurrence,recurrenceTime}});return commitment;}
  updateCommitment(id:string,input:Record<string,unknown>){const current=this.commitment(id);if(!current)return null;if('targetAt'in input&&input.targetAt&&!Number.isFinite(Date.parse(String(input.targetAt))))throw new Error('目标时间无效');const status=input.status==='completed'||input.status==='cancelled'||input.status==='active'?input.status:current.status,domainId=input.domainId&&this.domain(String(input.domainId))?String(input.domainId):current.domainId,description=String(input.description??current.description).trim().slice(0,1000)||current.description,recurrence='recurrence'in input?validRecurrence(input.recurrence):current.recurrence,recurrenceTime=recurrence==='daily'?validTime(input.recurrenceTime??current.recurrenceTime,''):null;if(recurrence==='daily'&&!recurrenceTime)throw new Error('每天重复需要选择跟进时间');const now=this.clock(),recurrenceChanged=recurrence!==current.recurrence||recurrenceTime!==current.recurrenceTime,daily=recurrence==='daily'&&recurrenceChanged?dailyTarget(now,recurrenceTime!,true):null,targetAt=daily?.toISOString()||('targetAt'in input?(input.targetAt?new Date(String(input.targetAt)).toISOString():null):current.targetAt);if(recurrence==='none'&&status==='active'&&!targetAt)throw new Error('请选择日期时间，或设为每天重复');const at=now.toISOString(),completedAt=status==='completed'?(current.completedAt||at):null,cycleKey=daily?dateKey(daily):recurrence==='daily'?current.cycleKey:null;this.db.db.prepare('UPDATE commitments SET domain_id=?,description=?,status=?,target_at=?,updated_at=?,completed_at=?,next_followup_at=?,recurrence=?,recurrence_time=?,cycle_key=?,cycle_followup_count=? WHERE id=?').run(domainId,description,status,targetAt,at,completedAt,status==='active'&&!recurrenceChanged?current.nextFollowUpAt:null,recurrence,recurrenceTime,cycleKey,recurrenceChanged?0:current.cycleFollowUpCount,id);const commitment=this.commitment(id)!;if(current.status!=='completed'&&status==='completed')this.events.emit({type:'commitment.completed',sourceType:'commitment',sourceId:id,title:'承诺完成',body:commitment.description});return commitment;}
  followUps(limit=100):CommitmentFollowUp[]{return(this.db.db.prepare('SELECT * FROM commitment_followups ORDER BY created_at DESC LIMIT ?').all(Math.max(1,Math.min(500,limit))) as any[]).map(this.mapFollowUp);}

  async pulse(){if(this.running)return this.snapshot();this.running=true;const at=this.clock();this.db.setSetting('cyberdaddyLastPulseAt',at.toISOString());try{
    if(!this.db.setting('cyberdaddyEnabled',false))return this.halt('CyberDaddy 未启用');
    if(this.db.setting('cyberdaddyPaused',false)||this.db.setting('proactivePaused',false))return this.halt('CyberDaddy 已暂停');
    if(this.isQuiet(at))return this.halt('当前处于安静时间');
    if(this.followUpsToday(at)>=this.dailyLimit)return this.halt('今天的主动跟进已经达到上限');
    this.advanceRecurring(at);const commitment=this.dueCommitments(at)[0];if(!commitment){const next=this.nextScheduled(at);return this.halt(next?`下一次跟进：${new Date(next.targetAt!).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`:'没有已安排时间的承诺');}
    const domain=this.domain(commitment.domainId)!;const decision=await this.evaluate(commitment,domain,at),sequence=commitment.followUpCount+1;let eventId:string|null=null;
    if(decision.message){const emitted=this.events.emit({type:'cyberdaddy.followup_due',sourceType:'commitment',sourceId:commitment.id,title:'Soren',body:decision.message,dedupeKey:`cyberdaddy:${commitment.id}:followup:${sequence}`,conversationId:commitment.sourceConversationId,payload:{domainId:domain.id,intensity:domain.intensity,action:decision.action}});eventId=emitted.event.id;}
    const delivered=Boolean(decision.message),next=decision.nextEligibleFollowUpAt||(!delivered?new Date(at.getTime()+60*60_000).toISOString():null);this.db.db.transaction(()=>{this.db.db.prepare('INSERT INTO commitment_followups VALUES (?,?,?,?,?,?,?)').run(crypto.randomUUID(),commitment.id,decision.action,decision.message,decision.reason,eventId,at.toISOString());this.db.db.prepare('UPDATE commitments SET last_followup_at=?,next_followup_at=?,followup_count=followup_count+?,cycle_followup_count=cycle_followup_count+?,updated_at=? WHERE id=?').run(delivered?at.toISOString():commitment.lastFollowUpAt,next,delivered?1:0,delivered?1:0,at.toISOString(),commitment.id);})();this.finish(`${domain.name} · ${decision.action} · ${decision.reason}`);
  }catch(error:any){this.finish(`跟进失败：${String(error?.message||error).slice(0,180)}`);}finally{this.running=false;}return this.snapshot();}

  private async evaluate(commitment:Commitment,domain:CyberDaddyDomain,at:Date){const input={commitment,domain,now:at,recentUserContext:this.recentUserContext(commitment)},simple=hasObviousHighBurden(input.recentUserContext)||commitment.recurrence==='daily'||(domain.intensity==='gentle'&&commitment.followUpCount===0),enabled=this.db.setting('cyberdaddyContextEvaluatorEnabled',false);if(simple||!enabled||!this.contextualEvaluator)return this.rules.evaluate(input);try{return await this.contextualEvaluator.evaluate(input);}catch{return this.rules.evaluate(input);}}
  private dueCommitments(at:Date){return(this.db.db.prepare(`SELECT commitments.*,cyberdaddy_domains.intensity domain_intensity FROM commitments JOIN cyberdaddy_domains ON cyberdaddy_domains.id=commitments.domain_id WHERE commitments.status='active' AND cyberdaddy_domains.enabled=1 AND commitments.target_at IS NOT NULL AND commitments.target_at<=? AND ((commitments.cycle_followup_count=0 AND commitments.last_followup_at IS NULL AND commitments.next_followup_at IS NULL) OR (commitments.next_followup_at IS NOT NULL AND commitments.next_followup_at<=?)) ORDER BY COALESCE(commitments.next_followup_at,commitments.target_at)`).all(at.toISOString(),at.toISOString()) as any[]).map(this.mapCommitment).filter(item=>(item.recurrence==='daily'?item.cycleFollowUpCount:item.followUpCount)<this.maxFollowUps(this.domain(item.domainId)?.intensity||'normal'));}
  private nextScheduled(at:Date){const row=this.db.db.prepare(`SELECT commitments.* FROM commitments JOIN cyberdaddy_domains ON cyberdaddy_domains.id=commitments.domain_id WHERE commitments.status='active' AND cyberdaddy_domains.enabled=1 AND commitments.target_at>? ORDER BY commitments.target_at LIMIT 1`).get(at.toISOString()) as any;return row?this.mapCommitment(row):null;}
  private advanceRecurring(at:Date){const today=dateKey(at),rows=this.db.db.prepare("SELECT * FROM commitments WHERE status='active' AND recurrence='daily' AND (cycle_key IS NULL OR cycle_key<?)").all(today) as any[];for(const row of rows){const commitment=this.mapCommitment(row),target=dailyTarget(at,commitment.recurrenceTime||'09:00',false);this.db.db.prepare('UPDATE commitments SET target_at=?,cycle_key=?,cycle_followup_count=0,last_followup_at=NULL,next_followup_at=NULL,updated_at=? WHERE id=?').run(target.toISOString(),today,at.toISOString(),commitment.id);}}
  private recentUserContext(commitment:Commitment){const rows=commitment.sourceConversationId?this.db.db.prepare(`SELECT content FROM messages WHERE conversation_id=? AND role='user' AND created_at>=? ORDER BY created_at DESC LIMIT 8`).all(commitment.sourceConversationId,commitment.createdAt):this.db.db.prepare(`SELECT content FROM messages WHERE role='user' AND created_at>=? ORDER BY created_at DESC LIMIT 8`).all(commitment.createdAt);return(rows as any[]).map(row=>row.content).join('\n');}
  private maxFollowUps(intensity:CyberDaddyIntensity){return intensity==='gentle'?1:intensity==='daddy'?5:3;}
  private followUpsToday(at:Date){const start=new Date(at);start.setHours(0,0,0,0);return Number((this.db.db.prepare("SELECT COUNT(*) count FROM commitment_followups WHERE message<>'' AND created_at>=?").get(start.toISOString()) as any).count);}
  private isQuiet(at:Date){const start=validTime(this.db.setting('cyberdaddyQuietStart','23:00'),'23:00'),end=validTime(this.db.setting('cyberdaddyQuietEnd','08:00'),'08:00'),minutes=at.getHours()*60+at.getMinutes(),startMinutes=Number(start.slice(0,2))*60+Number(start.slice(3)),endMinutes=Number(end.slice(0,2))*60+Number(end.slice(3));if(startMinutes===endMinutes)return false;return startMinutes<endMinutes?minutes>=startMinutes&&minutes<endMinutes:minutes>=startMinutes||minutes<endMinutes;}
  private ensureDomains(){const insert=this.db.db.prepare('INSERT OR IGNORE INTO cyberdaddy_domains VALUES (?,?,?,?,?,?,?)'),at=nowIso();for(const[id,name]of defaultDomains)insert.run(id,name,0,'normal','{}',at,at);}
  private domain(id:string){const row=this.db.db.prepare('SELECT * FROM cyberdaddy_domains WHERE id=?').get(id) as any;return row?this.mapDomain(row):null;}
  private commitment(id:string){const row=this.db.db.prepare('SELECT * FROM commitments WHERE id=?').get(id) as any;return row?this.mapCommitment(row):null;}
  private finish(outcome:string){this.db.setSetting('cyberdaddyLastOutcome',outcome);}
  private halt(outcome:string){this.finish(outcome);this.running=false;return this.snapshot();}
  private mapDomain=(row:any):CyberDaddyDomain=>({id:row.id,name:row.name,enabled:bool(row.enabled),intensity:validIntensity(row.intensity),settings:parse(row.settings_json,{}),createdAt:row.created_at,updatedAt:row.updated_at});
  private mapCommitment=(row:any):Commitment=>({id:row.id,domainId:row.domain_id,description:row.description,status:row.status,targetAt:row.target_at,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at,sourceConversationId:row.source_conversation_id,recurrence:validRecurrence(row.recurrence),recurrenceTime:row.recurrence_time,cycleKey:row.cycle_key,cycleFollowUpCount:Number(row.cycle_followup_count||0),lastFollowUpAt:row.last_followup_at,nextFollowUpAt:row.next_followup_at,followUpCount:Number(row.followup_count),metadata:parse(row.metadata_json,{})});
  private mapFollowUp=(row:any):CommitmentFollowUp=>({id:row.id,commitmentId:row.commitment_id,action:row.action,message:row.message,reason:row.reason,eventId:row.event_id,createdAt:row.created_at});
}
