import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { SorenDatabase } from './db.js';
import { EventService } from './event-service.js';
import { CyberDaddyService } from './cyberdaddy-service.js';

function setup(initial='2026-09-16T10:00:00+08:00'){const directory=mkdtempSync(join(tmpdir(),'soren-cyberdaddy-')),db=new SorenDatabase(join(directory,'soren.db')),events=new EventService(db);let current=new Date(initial);const service=new CyberDaddyService(db,events,()=>new Date(current));return{directory,db,events,service,setTime:(value:string)=>{current=new Date(value);}};}
function enable(service:CyberDaddyService,domainId='study',intensity:'gentle'|'normal'|'daddy'='normal'){service.updateConfig({enabled:true,quietStart:'23:00',quietEnd:'08:00'});service.updateDomain(domainId,{enabled:true,intensity});}

test('disabled domains and global pause never send follow-ups',async()=>{const{directory,db,service}=setup();try{service.updateConfig({enabled:true,quietStart:'23:00',quietEnd:'08:00'});service.createCommitment({domainId:'study',description:'练习听力',targetAt:'2026-09-16T09:00:00+08:00'});await service.pulse();assert.equal(service.followUps().length,0);service.updateDomain('study',{enabled:true});service.updateConfig({paused:true});await service.pulse();assert.equal(service.followUps().length,0);assert.equal(db.conversations().length,0);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('quiet hours block delivery without consuming the commitment',async()=>{const{directory,db,service}=setup('2026-09-16T23:30:00+08:00');try{enable(service);service.createCommitment({domainId:'study',description:'背单词',targetAt:'2026-09-16T22:00:00+08:00'});await service.pulse();assert.equal(service.followUps().length,0);assert.match(service.snapshot().lastOutcome,/安静时间/);assert.equal(service.commitments()[0].followUpCount,0);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('Gentle sends one reminder while Daddy Mode can follow up without duplicates',async()=>{const gentle=setup();try{enable(gentle.service,'study','gentle');gentle.service.createCommitment({domainId:'study',description:'做一组听力',targetAt:'2026-09-16T09:00:00+08:00'});await gentle.service.pulse();gentle.setTime('2026-09-17T10:00:00+08:00');await gentle.service.pulse();assert.equal(gentle.service.followUps().filter(item=>item.message).length,1);assert.match(gentle.service.followUps()[0].message,/不急着现在回/);}finally{gentle.db.db.close();rmSync(gentle.directory,{recursive:true,force:true});}
  const daddy=setup();try{enable(daddy.service,'projects','daddy');const commitment=daddy.service.createCommitment({domainId:'projects',description:'完成 SorenOS 设置页',targetAt:'2026-09-16T09:00:00+08:00'});await daddy.service.pulse();await daddy.service.pulse();assert.equal(daddy.service.followUps().filter(item=>item.message).length,1);daddy.setTime('2026-09-16T11:31:00+08:00');await daddy.service.pulse();assert.equal(daddy.service.followUps().filter(item=>item.message).length,2);assert.equal(daddy.events.events().filter(item=>item.sourceId===commitment.id&&item.type==='cyberdaddy.followup_due').length,2);assert.equal(daddy.db.messages(daddy.db.conversations()[0].id).length,2);}finally{daddy.db.db.close();rmSync(daddy.directory,{recursive:true,force:true});}});

test('recent difficult context reduces the task in the same Soren conversation',async()=>{const{directory,db,service}=setup();try{enable(service,'fitness','normal');const conversation=db.createConversation('日常');const commitment=service.createCommitment({domainId:'fitness',description:'跑步半小时',targetAt:'2026-09-16T09:00:00+08:00',sourceConversationId:conversation.id});db.addMessage(conversation.id,'user','今天家里有急事，人也很累。');await service.pulse();const follow=service.followUps()[0];assert.equal(follow.action,'REDUCE_TASK');assert.match(follow.message,/缩小|十分钟/);assert.equal(db.messages(conversation.id).at(-1)?.role,'assistant');assert.equal(service.commitments()[0].id,commitment.id);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('completed commitments never become eligible again',async()=>{const{directory,db,service}=setup();try{enable(service);const commitment=service.createCommitment({domainId:'study',description:'写完练习',targetAt:'2026-09-16T09:00:00+08:00'});service.updateCommitment(commitment.id,{status:'completed'});await service.pulse();assert.equal(service.followUps().length,0);assert.equal(db.conversations().length,0);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('configuration, commitments and follow-up history survive a database restart',async()=>{const directory=mkdtempSync(join(tmpdir(),'soren-cyberdaddy-restart-')),file=join(directory,'soren.db');try{const firstDb=new SorenDatabase(file),firstEvents=new EventService(firstDb),first=new CyberDaddyService(firstDb,firstEvents,()=>new Date('2026-09-16T10:00:00+08:00'));enable(first,'career','daddy');const commitment=first.createCommitment({domainId:'career',description:'投递一份简历',targetAt:'2026-09-16T09:00:00+08:00'});await first.pulse();firstDb.db.close();const secondDb=new SorenDatabase(file),second=new CyberDaddyService(secondDb,new EventService(secondDb),()=>new Date('2026-09-16T10:05:00+08:00')),snapshot=second.snapshot();assert.equal(snapshot.enabled,true);assert.equal(snapshot.domains.find(item=>item.id==='career')?.intensity,'daddy');assert.equal(snapshot.commitments.find(item=>item.id===commitment.id)?.followUpCount,1);assert.equal(snapshot.followUps[0].commitmentId,commitment.id);assert.equal(secondDb.messages(secondDb.conversations()[0].id).length,1);secondDb.db.close();}finally{rmSync(directory,{recursive:true,force:true});}});
