import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { SorenDatabase } from './db.js';
import { EventService } from './event-service.js';
import { CyberDaddyService } from './cyberdaddy-service.js';
import type { CyberDaddyContextEvaluator } from './cyberdaddy-evaluator.js';

function setup(initial='2026-09-16T10:00:00+08:00',evaluator:CyberDaddyContextEvaluator|null=null){const directory=mkdtempSync(join(tmpdir(),'soren-cyberdaddy-')),db=new SorenDatabase(join(directory,'soren.db')),events=new EventService(db);let current=new Date(initial);const service=new CyberDaddyService(db,events,()=>new Date(current),evaluator);return{directory,db,events,service,setTime:(value:string)=>{current=new Date(value);}};}
function enable(service:CyberDaddyService,domainId='study',intensity:'gentle'|'normal'|'daddy'='normal'){service.updateConfig({enabled:true,quietStart:'23:00',quietEnd:'08:00'});service.updateDomain(domainId,{enabled:true,intensity});}

test('disabled domains and global pause never send follow-ups',async()=>{const{directory,db,service}=setup();try{service.updateConfig({enabled:true,quietStart:'23:00',quietEnd:'08:00'});service.createCommitment({domainId:'study',description:'练习听力',targetAt:'2026-09-16T09:00:00+08:00'});await service.pulse();assert.equal(service.followUps().length,0);service.updateDomain('study',{enabled:true});service.updateConfig({paused:true});await service.pulse();assert.equal(service.followUps().length,0);assert.equal(db.conversations().length,0);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('quiet hours block delivery without consuming the commitment',async()=>{const{directory,db,service}=setup('2026-09-16T23:30:00+08:00');try{enable(service);service.createCommitment({domainId:'study',description:'背单词',targetAt:'2026-09-16T22:00:00+08:00'});await service.pulse();assert.equal(service.followUps().length,0);assert.match(service.snapshot().lastOutcome,/安静时间/);assert.equal(service.commitments()[0].followUpCount,0);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('Gentle sends one reminder while Daddy Mode can follow up without duplicates',async()=>{const gentle=setup();try{enable(gentle.service,'study','gentle');gentle.service.createCommitment({domainId:'study',description:'做一组听力',targetAt:'2026-09-16T09:00:00+08:00'});await gentle.service.pulse();gentle.setTime('2026-09-17T10:00:00+08:00');await gentle.service.pulse();assert.equal(gentle.service.followUps().filter(item=>item.message).length,1);assert.match(gentle.service.followUps()[0].message,/不急着现在回/);}finally{gentle.db.db.close();rmSync(gentle.directory,{recursive:true,force:true});}
  const daddy=setup();try{enable(daddy.service,'projects','daddy');const commitment=daddy.service.createCommitment({domainId:'projects',description:'完成 SorenOS 设置页',targetAt:'2026-09-16T09:00:00+08:00'});await daddy.service.pulse();await daddy.service.pulse();assert.equal(daddy.service.followUps().filter(item=>item.message).length,1);daddy.setTime('2026-09-16T11:31:00+08:00');await daddy.service.pulse();assert.equal(daddy.service.followUps().filter(item=>item.message).length,2);assert.equal(daddy.events.events().filter(item=>item.sourceId===commitment.id&&item.type==='cyberdaddy.followup_due').length,2);assert.equal(daddy.db.messages(daddy.db.conversations()[0].id).length,2);}finally{daddy.db.db.close();rmSync(daddy.directory,{recursive:true,force:true});}});

test('recent difficult context reduces the task in the same Soren conversation',async()=>{const{directory,db,service}=setup();try{enable(service,'fitness','normal');const conversation=db.createConversation('日常');const commitment=service.createCommitment({domainId:'fitness',description:'跑步半小时',targetAt:'2026-09-16T09:00:00+08:00',sourceConversationId:conversation.id});db.addMessage(conversation.id,'user','今天家里有急事，人也很累。');await service.pulse();const follow=service.followUps()[0];assert.equal(follow.action,'REDUCE_TASK');assert.match(follow.message,/缩小|十分钟/);assert.equal(db.messages(conversation.id).at(-1)?.role,'assistant');assert.equal(service.commitments()[0].id,commitment.id);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('completed commitments never become eligible again',async()=>{const{directory,db,service}=setup();try{enable(service);const commitment=service.createCommitment({domainId:'study',description:'写完练习',targetAt:'2026-09-16T09:00:00+08:00'});service.updateCommitment(commitment.id,{status:'completed'});await service.pulse();assert.equal(service.followUps().length,0);assert.equal(db.conversations().length,0);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('configuration, commitments and follow-up history survive a database restart',async()=>{const directory=mkdtempSync(join(tmpdir(),'soren-cyberdaddy-restart-')),file=join(directory,'soren.db');try{const firstDb=new SorenDatabase(file),firstEvents=new EventService(firstDb),first=new CyberDaddyService(firstDb,firstEvents,()=>new Date('2026-09-16T10:00:00+08:00'));enable(first,'career','daddy');const commitment=first.createCommitment({domainId:'career',description:'投递一份简历',targetAt:'2026-09-16T09:00:00+08:00'});await first.pulse();firstDb.db.close();const secondDb=new SorenDatabase(file),second=new CyberDaddyService(secondDb,new EventService(secondDb),()=>new Date('2026-09-16T10:05:00+08:00')),snapshot=second.snapshot();assert.equal(snapshot.enabled,true);assert.equal(snapshot.domains.find(item=>item.id==='career')?.intensity,'daddy');assert.equal(snapshot.commitments.find(item=>item.id===commitment.id)?.followUpCount,1);assert.equal(snapshot.followUps[0].commitmentId,commitment.id);assert.equal(secondDb.messages(secondDb.conversations()[0].id).length,1);secondDb.db.close();}finally{rmSync(directory,{recursive:true,force:true});}});

test('daily commitments reset their cycle and become eligible again the next day',async()=>{const{directory,db,service,setTime}=setup('2026-09-16T19:00:00+08:00');try{enable(service,'sleep','daddy');service.updateConfig({quietStart:'00:00',quietEnd:'00:00'});const commitment=service.createCommitment({domainId:'sleep',description:'十二点前睡觉',recurrence:'daily',recurrenceTime:'20:00'});assert.equal(commitment.recurrence,'daily');assert.equal(commitment.cycleKey,'2026-09-16');await service.pulse();assert.match(service.snapshot().lastOutcome,/下一次跟进/);setTime('2026-09-16T20:01:00+08:00');await service.pulse();await service.pulse();assert.equal(service.followUps().length,1);assert.match(service.followUps()[0].message,/别拿明天替今天/);setTime('2026-09-17T20:01:00+08:00');await service.pulse();const current=service.commitments()[0];assert.equal(service.followUps().length,2);assert.equal(current.followUpCount,2);assert.equal(current.cycleFollowUpCount,1);assert.equal(current.cycleKey,'2026-09-17');}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('an unscheduled one-time commitment is rejected instead of silently doing nothing',()=>{const{directory,db,service}=setup();try{enable(service);assert.throws(()=>service.createCommitment({domainId:'study',description:'没有时间的任务'}),/请选择日期时间/);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('global disable and cancellation immediately before pulse remain silent',async()=>{const{directory,db,service}=setup();try{service.updateDomain('study',{enabled:true});const disabled=service.createCommitment({domainId:'study',description:'全局关闭时不提醒',targetAt:'2026-09-16T09:00:00+08:00'});await service.pulse();assert.equal(service.followUps().length,0);service.updateConfig({enabled:true});service.updateCommitment(disabled.id,{status:'cancelled'});await service.pulse();assert.equal(service.followUps().length,0);assert.equal(db.conversations().length,0);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('daily limit caps delivery at six messages',async()=>{const{directory,db,service}=setup();try{enable(service,'study','normal');for(let index=0;index<7;index++)service.createCommitment({domainId:'study',description:`任务 ${index}`,targetAt:'2026-09-16T09:00:00+08:00'});for(let index=0;index<8;index++)await service.pulse();assert.equal(service.followUps().length,6);assert.match(service.snapshot().lastOutcome,/上限/);assert.equal(db.messages(db.conversations()[0].id).length,6);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('simultaneous due commitments are handled fairly one per pulse',async()=>{const{directory,db,service}=setup();try{enable(service,'projects','normal');const first=service.createCommitment({domainId:'projects',description:'同时任务 A',targetAt:'2026-09-16T09:00:00+08:00'}),second=service.createCommitment({domainId:'projects',description:'同时任务 B',targetAt:'2026-09-16T09:00:00+08:00'});await service.pulse();assert.equal(service.followUps().length,1);await service.pulse();assert.deepEqual(new Set(service.followUps().map(item=>item.commitmentId)),new Set([first.id,second.id]));}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('duplicate concurrent pulse produces one follow-up',async()=>{let calls=0;const evaluator:CyberDaddyContextEvaluator={evaluate:async()=>{calls++;await Promise.resolve();return{action:'REMIND',message:'只发一次',reason:'test',nextEligibleFollowUpAt:null};}},setupResult=setup('2026-09-16T10:00:00+08:00',evaluator),{directory,db,service}=setupResult;try{enable(service,'career','normal');db.setSetting('cyberdaddyContextEvaluatorEnabled',true);service.createCommitment({domainId:'career',description:'并发测试',targetAt:'2026-09-16T09:00:00+08:00'});await Promise.all([service.pulse(),service.pulse()]);assert.equal(calls,1);assert.equal(service.followUps().length,1);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('context evaluator failure falls back to rules and preflight gates avoid evaluator calls',async()=>{let calls=0;const evaluator:CyberDaddyContextEvaluator={evaluate:async()=>{calls++;throw new Error('evaluator offline');}},{directory,db,service}=setup('2026-09-16T10:00:00+08:00',evaluator);try{service.updateDomain('career',{enabled:true,intensity:'normal'});db.setSetting('cyberdaddyContextEvaluatorEnabled',true);service.createCommitment({domainId:'career',description:'更新简历',targetAt:'2026-09-16T09:00:00+08:00'});await service.pulse();assert.equal(calls,0);service.updateConfig({enabled:true,paused:true});await service.pulse();assert.equal(calls,0);service.updateConfig({paused:false,quietStart:'23:00',quietEnd:'08:00'});await service.pulse();assert.equal(calls,1);assert.match(service.followUps()[0].message,/更新简历/);}finally{db.db.close();rmSync(directory,{recursive:true,force:true});}});

test('context evaluator NO_ACTION receives a cooldown instead of running every pulse',async()=>{let calls=0;const evaluator:CyberDaddyContextEvaluator={evaluate:async()=>{calls++;return{action:'NO_ACTION',message:'',reason:'现在不适合打扰',nextEligibleFollowUpAt:null};}},{directory,db,service}=setup('2026-09-16T10:00:00+08:00',evaluator);try{enable(service,'career','normal');db.setSetting('cyberdaddyContextEvaluatorEnabled',true);service.createCommitment({domainId:'career',description:'稍后再问',targetAt:'2026-09-16T09:00:00+08:00'});await service.pulse();await service.pulse();assert.equal(calls,1);assert.equal(db.messages(db.conversations()[0]?.id||'missing').length,0);assert.ok(service.commitments()[0].nextFollowUpAt);}finally{db.close();rmSync(directory,{recursive:true,force:true});}});

test('restart preserves the next follow-up and resumes it once eligible',async()=>{const directory=mkdtempSync(join(tmpdir(),'soren-cyberdaddy-next-')),file=join(directory,'soren.db');try{const firstDb=new SorenDatabase(file),first=new CyberDaddyService(firstDb,new EventService(firstDb),()=>new Date('2026-09-16T10:00:00+08:00'));enable(first,'projects','daddy');const commitment=first.createCommitment({domainId:'projects',description:'重启后继续',targetAt:'2026-09-16T09:00:00+08:00'});await first.pulse();const next=first.commitments()[0].nextFollowUpAt;assert.ok(next);firstDb.db.close();const secondDb=new SorenDatabase(file),second=new CyberDaddyService(secondDb,new EventService(secondDb),()=>new Date('2026-09-16T11:31:00+08:00'));await second.pulse();assert.equal(second.followUps().filter(item=>item.commitmentId===commitment.id).length,2);secondDb.db.close();}finally{rmSync(directory,{recursive:true,force:true});}});
