import type { Commitment, CommitmentFollowUp, CyberDaddyDomain, CyberDaddyIntensity, CyberDaddySnapshot, FollowUpAction } from '@soren/shared';
import type { SorenDatabase } from './db.js';
import type { EventService } from './event-service.js';

const nowIso=()=>new Date().toISOString();
const parse=<T>(value:unknown,fallback:T):T=>{try{return JSON.parse(String(value)) as T;}catch{return fallback;}};
const bool=(value:unknown)=>Boolean(Number(value));
const validIntensity=(value:unknown):CyberDaddyIntensity=>value==='gentle'||value==='daddy'?value:'normal';
const validTime=(value:unknown,fallback:string)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(value||''))?String(value):fallback;
const addMinutes=(date:Date,minutes:number)=>new Date(date.getTime()+minutes*60_000).toISOString();

const defaultDomains=[
  ['sleep','作息'],['study','学习 / IELTS'],['career','求职'],['fitness','运动'],['projects','个人项目'],['habits','生活习惯']
] as const;

interface Decision {action:FollowUpAction;message:string;reason:string;nextMinutes:number|null;}

export class CyberDaddyService {
  private timer:NodeJS.Timeout|null=null;
  private running=false;
  readonly dailyLimit=6;
  constructor(private readonly db:SorenDatabase,private readonly events:EventService,private readonly clock:()=>Date=()=>new Date()){this.ensureDomains();}

  start(){if(this.timer)return;this.timer=setInterval(()=>void this.pulse(),60_000);this.timer.unref();void this.pulse();}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
  snapshot():CyberDaddySnapshot{const current=this.clock();return{enabled:this.db.setting('cyberdaddyEnabled',false),paused:this.db.setting('cyberdaddyPaused',false)||this.db.setting('proactivePaused',false),quietStart:this.db.setting('cyberdaddyQuietStart','23:00'),quietEnd:this.db.setting('cyberdaddyQuietEnd','08:00'),inQuietHours:this.isQuiet(current),running:this.running,lastPulseAt:this.db.setting<string|null>('cyberdaddyLastPulseAt',null),lastOutcome:this.db.setting('cyberdaddyLastOutcome','尚未运行'),domains:this.domains(),commitments:this.commitments(),followUps:this.followUps()};}
  updateConfig(input:Record<string,unknown>){if('enabled'in input)this.db.setSetting('cyberdaddyEnabled',Boolean(input.enabled));if('paused'in input)this.db.setSetting('cyberdaddyPaused',Boolean(input.paused));if('quietStart'in input)this.db.setSetting('cyberdaddyQuietStart',validTime(input.quietStart,'23:00'));if('quietEnd'in input)this.db.setSetting('cyberdaddyQuietEnd',validTime(input.quietEnd,'08:00'));return this.snapshot();}
  domains():CyberDaddyDomain[]{return(this.db.db.prepare('SELECT * FROM cyberdaddy_domains ORDER BY created_at').all() as any[]).map(this.mapDomain);}
  updateDomain(id:string,input:Record<string,unknown>){const current=this.domain(id);if(!current)return null;const at=nowIso(),name=String(input.name??current.name).trim().slice(0,80)||current.name,enabled='enabled'in input?Boolean(input.enabled):current.enabled,intensity=validIntensity(input.intensity??current.intensity),settings=input.settings&&typeof input.settings==='object'?input.settings:current.settings;this.db.db.prepare('UPDATE cyberdaddy_domains SET name=?,enabled=?,intensity=?,settings_json=?,updated_at=? WHERE id=?').run(name,enabled?1:0,intensity,JSON.stringify(settings),at,id);return this.domain(id);}
  commitments(status=''):Commitment[]{return(this.db.db.prepare(`SELECT * FROM commitments WHERE (?='' OR status=?) ORDER BY CASE status WHEN 'active' THEN 0 ELSE 1 END,COALESCE(target_at,created_at)`).all(status,status) as any[]).map(this.mapCommitment);}
  createCommitment(input:Record<string,unknown>){const domainId=String(input.domainId||''),domain=this.domain(domainId),description=String(input.description||'').trim();if(!domain)throw new Error('监督领域不存在');if(!description)throw new Error('承诺内容不能为空');if(input.targetAt&&!Number.isFinite(Date.parse(String(input.targetAt))))throw new Error('目标时间无效');const targetAt=input.targetAt?new Date(String(input.targetAt)).toISOString():null,id=crypto.randomUUID(),at=this.clock().toISOString();this.db.db.prepare(`INSERT INTO commitments (id,domain_id,description,status,target_at,created_at,updated_at,completed_at,source_conversation_id,last_followup_at,next_followup_at,followup_count,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,domainId,description.slice(0,1000),'active',targetAt,at,at,null,input.sourceConversationId?String(input.sourceConversationId):null,null,null,0,JSON.stringify(input.metadata&&typeof input.metadata==='object'?input.metadata:{}));const commitment=this.commitment(id)!;this.events.emit({type:'commitment.created',sourceType:'commitment',sourceId:id,title:domain.name,body:commitment.description,payload:{domainId,targetAt}});return commitment;}
  updateCommitment(id:string,input:Record<string,unknown>){const current=this.commitment(id);if(!current)return null;if('targetAt'in input&&input.targetAt&&!Number.isFinite(Date.parse(String(input.targetAt))))throw new Error('目标时间无效');const status=input.status==='completed'||input.status==='cancelled'||input.status==='active'?input.status:current.status,domainId=input.domainId&&this.domain(String(input.domainId))?String(input.domainId):current.domainId,description=String(input.description??current.description).trim().slice(0,1000)||current.description,targetAt='targetAt'in input?(input.targetAt?new Date(String(input.targetAt)).toISOString():null):current.targetAt,at=this.clock().toISOString(),completedAt=status==='completed'?(current.completedAt||at):null;this.db.db.prepare('UPDATE commitments SET domain_id=?,description=?,status=?,target_at=?,updated_at=?,completed_at=?,next_followup_at=? WHERE id=?').run(domainId,description,status,targetAt,at,completedAt,status==='active'?current.nextFollowUpAt:null,id);const commitment=this.commitment(id)!;if(current.status!=='completed'&&status==='completed')this.events.emit({type:'commitment.completed',sourceType:'commitment',sourceId:id,title:'承诺完成',body:commitment.description});return commitment;}
  followUps(limit=100):CommitmentFollowUp[]{return(this.db.db.prepare('SELECT * FROM commitment_followups ORDER BY created_at DESC LIMIT ?').all(Math.max(1,Math.min(500,limit))) as any[]).map(this.mapFollowUp);}

  async pulse(){if(this.running)return this.snapshot();this.running=true;const at=this.clock();this.db.setSetting('cyberdaddyLastPulseAt',at.toISOString());try{
    if(!this.db.setting('cyberdaddyEnabled',false))return this.halt('CyberDaddy 未启用');
    if(this.db.setting('cyberdaddyPaused',false)||this.db.setting('proactivePaused',false))return this.halt('CyberDaddy 已暂停');
    if(this.isQuiet(at))return this.halt('当前处于安静时间');
    if(this.followUpsToday(at)>=this.dailyLimit)return this.halt('今天的主动跟进已经达到上限');
    const commitment=this.dueCommitments(at)[0];if(!commitment)return this.halt('没有需要跟进的承诺');
    const domain=this.domain(commitment.domainId)!;const decision=this.evaluate(commitment,domain,at),sequence=commitment.followUpCount+1;let eventId:string|null=null;
    if(decision.message){const emitted=this.events.emit({type:'cyberdaddy.followup_due',sourceType:'commitment',sourceId:commitment.id,title:'Soren',body:decision.message,dedupeKey:`cyberdaddy:${commitment.id}:followup:${sequence}`,conversationId:commitment.sourceConversationId,payload:{domainId:domain.id,intensity:domain.intensity,action:decision.action}});eventId=emitted.event.id;}
    const delivered=Boolean(decision.message),next=decision.nextMinutes==null?null:addMinutes(at,decision.nextMinutes);this.db.db.transaction(()=>{this.db.db.prepare('INSERT INTO commitment_followups VALUES (?,?,?,?,?,?,?)').run(crypto.randomUUID(),commitment.id,decision.action,decision.message,decision.reason,eventId,at.toISOString());this.db.db.prepare('UPDATE commitments SET last_followup_at=?,next_followup_at=?,followup_count=followup_count+?,updated_at=? WHERE id=?').run(delivered?at.toISOString():commitment.lastFollowUpAt,next,delivered?1:0,at.toISOString(),commitment.id);})();this.finish(`${domain.name} · ${decision.action} · ${decision.reason}`);
  }catch(error:any){this.finish(`跟进失败：${String(error?.message||error).slice(0,180)}`);}finally{this.running=false;}return this.snapshot();}

  private evaluate(commitment:Commitment,domain:CyberDaddyDomain,at:Date):Decision{const context=this.recentUserContext(commitment),burden=/(累|疲惫|生病|不舒服|医院|家里.{0,6}(急事|出事)|急事|崩溃|失眠|没睡|exhausted|sick|emergency)/i.test(context),count=commitment.followUpCount;
    if(burden)return{action:count?'CHECK_IN':'REDUCE_TASK',message:count?`今天状态不对，这件事先不追进度。你只要告诉我：继续、缩小，还是推迟。`:`我记得你答应了「${commitment.description}」。但今天先缩小一点，做十分钟就算开始；实在不行就告诉我推迟。`,reason:'近期聊天显示用户负担较重',nextMinutes:domain.intensity==='daddy'?180:720};
    if(domain.intensity==='gentle')return{action:'REMIND',message:`提醒一下：${commitment.description}。不急着现在回。`,reason:'Gentle 只做一次轻提醒',nextMinutes:null};
    if(domain.intensity==='daddy'){const messages=count===0?`该兑现了：${commitment.description}。告诉我你现在开始，还是给我一个明确的新时间。`:count===1?`我还记得「${commitment.description}」。进度给我，哪怕只做了第一步。`:`回来确认一下：${commitment.description}。继续、缩小，或者改时间，选一个。`;return{action:count?'FOLLOW_UP':'REMIND',message:messages,reason:count?'Daddy Mode 持续但有限地跟进':'承诺已到期',nextMinutes:[90,180,360,720][Math.min(count,3)]};}
    return{action:count?'FOLLOW_UP':'REMIND',message:count?`我回来确认一下「${commitment.description}」。做了多少，或者需要改到几点？`:`你之前答应了「${commitment.description}」。现在还做吗？`,reason:count?'Normal 对未完成承诺进行有限跟进':'承诺已到期',nextMinutes:count>=2?null:count===1?720:240};
  }
  private dueCommitments(at:Date){return(this.db.db.prepare(`SELECT commitments.*,cyberdaddy_domains.intensity domain_intensity FROM commitments JOIN cyberdaddy_domains ON cyberdaddy_domains.id=commitments.domain_id WHERE commitments.status='active' AND cyberdaddy_domains.enabled=1 AND commitments.target_at IS NOT NULL AND commitments.target_at<=? AND ((commitments.followup_count=0 AND commitments.last_followup_at IS NULL) OR (commitments.next_followup_at IS NOT NULL AND commitments.next_followup_at<=?)) ORDER BY COALESCE(commitments.next_followup_at,commitments.target_at)`).all(at.toISOString(),at.toISOString()) as any[]).map(this.mapCommitment).filter(item=>item.followUpCount<this.maxFollowUps(this.domain(item.domainId)?.intensity||'normal'));}
  private recentUserContext(commitment:Commitment){const rows=commitment.sourceConversationId?this.db.db.prepare(`SELECT content FROM messages WHERE conversation_id=? AND role='user' AND created_at>=? ORDER BY created_at DESC LIMIT 8`).all(commitment.sourceConversationId,commitment.createdAt):this.db.db.prepare(`SELECT content FROM messages WHERE role='user' AND created_at>=? ORDER BY created_at DESC LIMIT 8`).all(commitment.createdAt);return(rows as any[]).map(row=>row.content).join('\n');}
  private maxFollowUps(intensity:CyberDaddyIntensity){return intensity==='gentle'?1:intensity==='daddy'?5:3;}
  private followUpsToday(at:Date){const start=new Date(at);start.setHours(0,0,0,0);return Number((this.db.db.prepare("SELECT COUNT(*) count FROM commitment_followups WHERE message<>'' AND created_at>=?").get(start.toISOString()) as any).count);}
  private isQuiet(at:Date){const start=validTime(this.db.setting('cyberdaddyQuietStart','23:00'),'23:00'),end=validTime(this.db.setting('cyberdaddyQuietEnd','08:00'),'08:00'),minutes=at.getHours()*60+at.getMinutes(),startMinutes=Number(start.slice(0,2))*60+Number(start.slice(3)),endMinutes=Number(end.slice(0,2))*60+Number(end.slice(3));if(startMinutes===endMinutes)return false;return startMinutes<endMinutes?minutes>=startMinutes&&minutes<endMinutes:minutes>=startMinutes||minutes<endMinutes;}
  private ensureDomains(){const insert=this.db.db.prepare('INSERT OR IGNORE INTO cyberdaddy_domains VALUES (?,?,?,?,?,?,?)'),at=nowIso();for(const[id,name]of defaultDomains)insert.run(id,name,0,'normal','{}',at,at);}
  private domain(id:string){const row=this.db.db.prepare('SELECT * FROM cyberdaddy_domains WHERE id=?').get(id) as any;return row?this.mapDomain(row):null;}
  private commitment(id:string){const row=this.db.db.prepare('SELECT * FROM commitments WHERE id=?').get(id) as any;return row?this.mapCommitment(row):null;}
  private finish(outcome:string){this.db.setSetting('cyberdaddyLastOutcome',outcome);}
  private halt(outcome:string){this.finish(outcome);this.running=false;return this.snapshot();}
  private mapDomain=(row:any):CyberDaddyDomain=>({id:row.id,name:row.name,enabled:bool(row.enabled),intensity:validIntensity(row.intensity),settings:parse(row.settings_json,{}),createdAt:row.created_at,updatedAt:row.updated_at});
  private mapCommitment=(row:any):Commitment=>({id:row.id,domainId:row.domain_id,description:row.description,status:row.status,targetAt:row.target_at,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at,sourceConversationId:row.source_conversation_id,lastFollowUpAt:row.last_followup_at,nextFollowUpAt:row.next_followup_at,followUpCount:Number(row.followup_count),metadata:parse(row.metadata_json,{})});
  private mapFollowUp=(row:any):CommitmentFollowUp=>({id:row.id,commitmentId:row.commitment_id,action:row.action,message:row.message,reason:row.reason,eventId:row.event_id,createdAt:row.created_at});
}
