import { networkInterfaces,type NetworkInterfaceInfo } from 'node:os';
import { X509Certificate } from 'node:crypto';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import forge from 'node-forge';

export interface LanCertificateMetadata{lanIps:string[];createdAt:string;expiresAt:string;}
export interface NetworkConfig{lanMode:boolean;host:'127.0.0.1';port:number;lanHost:'0.0.0.0'|null;lanPort:number|null;protocol:'http'|'https';phoneUrl:string|null;authentication:false;certificate:{ready:boolean;reason:string;certPath:string;keyPath:string;caPath:string;lanIps:string[]};}
export const LAN_WARNING='LAN Test Mode: ENABLED\nTrusted private LAN only.\nNo authentication is enabled.\nDo not use on public/shared Wi-Fi.';
type Interfaces=NodeJS.Dict<NetworkInterfaceInfo[]>;
const virtualName=/virtual|vethernet|wsl|vmware|virtualbox|hyper-v|tailscale|loopback/i;
export const isPrivateIpv4=(address:string)=>/^10\./.test(address)||/^192\.168\./.test(address)||(()=>{const match=address.match(/^172\.(\d+)\./);return Boolean(match&&Number(match[1])>=16&&Number(match[1])<=31);})();
export function detectLanIpv4s(source:Interfaces=networkInterfaces()){const found:Object[]=[];for(const[name,entries]of Object.entries(source)){if(virtualName.test(name))continue;for(const entry of entries||[])if(entry.family==='IPv4'&&!entry.internal&&isPrivateIpv4(entry.address))found.push({address:entry.address,preferred:/wi-?fi|wlan|wireless|无线|ethernet|以太网/i.test(name)?0:1,name});}return(found as {address:string;preferred:number;name:string}[]).sort((a,b)=>a.preferred-b.preferred||a.name.localeCompare(b.name)).map(item=>item.address).filter((value,index,array)=>array.indexOf(value)===index);}
export function parseLanMode(value:unknown){if(value===undefined||value===''||value==='false')return false;if(value==='true')return true;throw new Error('SOREN_LAN_MODE 只接受 true 或 false');}
export const lanPaths=(appRoot:string)=>{const root=join(appRoot,'.lan');return{root,certPath:join(root,'soren-lan-cert.pem'),keyPath:join(root,'soren-lan-key.pem'),caPath:join(root,'soren-lan-ca.crt'),metadataPath:join(root,'metadata.json')};};
async function readMetadata(path:string){return JSON.parse(await readFile(path,'utf8')) as LanCertificateMetadata;}
export async function certificateStatus(appRoot:string,lanIps=detectLanIpv4s()){const paths=lanPaths(appRoot);try{const[certPem,metadata]=await Promise.all([readFile(paths.certPath,'utf8'),readMetadata(paths.metadataPath),readFile(paths.keyPath,'utf8'),readFile(paths.caPath,'utf8')]),certificate=new X509Certificate(certPem),missing=lanIps.filter(ip=>!certificate.checkIP(ip));if(!lanIps.length)return{...paths,ready:false,reason:'没有检测到可信私人局域网 IPv4 地址',lanIps};if(Date.parse(certificate.validTo)<=Date.now())return{...paths,ready:false,reason:'HTTPS 证书已过期，请重新运行 pnpm lan:setup',lanIps};if(missing.length)return{...paths,ready:false,reason:`当前 LAN IP ${missing.join('、')} 不在证书中，请重新运行 pnpm lan:setup`,lanIps};return{...paths,ready:true,reason:'HTTPS 证书与当前 LAN IP 匹配',lanIps,metadata};}catch{return{...paths,ready:false,reason:'尚未生成 LAN HTTPS 证书，请先运行 pnpm lan:setup',lanIps};}}
const serial=()=>forge.util.bytesToHex(forge.random.getBytesSync(16)).replace(/^0/,'1');
export async function setupLanCertificate(appRoot:string,lanIps=detectLanIpv4s()){if(!lanIps.length)throw new Error('没有检测到私人 LAN IPv4。请确认电脑已连接家庭 Wi-Fi 或私人有线网络。');const paths=lanPaths(appRoot),now=new Date(),expires=new Date(now);expires.setDate(expires.getDate()+365);const caKeys=forge.pki.rsa.generateKeyPair(2048),ca=forge.pki.createCertificate();ca.publicKey=caKeys.publicKey;ca.serialNumber=serial();ca.validity.notBefore=new Date(now.getTime()-86_400_000);ca.validity.notAfter=expires;const caName=[{name:'commonName',value:'SorenOS LAN Test CA'},{name:'organizationName',value:'SorenOS Local'}];ca.setSubject(caName);ca.setIssuer(caName);ca.setExtensions([{name:'basicConstraints',cA:true,critical:true},{name:'keyUsage',keyCertSign:true,cRLSign:true,critical:true},{name:'subjectKeyIdentifier'}]);ca.sign(caKeys.privateKey,forge.md.sha256.create());const serverKeys=forge.pki.rsa.generateKeyPair(2048),cert=forge.pki.createCertificate();cert.publicKey=serverKeys.publicKey;cert.serialNumber=serial();cert.validity.notBefore=new Date(now.getTime()-86_400_000);cert.validity.notAfter=expires;cert.setSubject([{name:'commonName',value:'SorenOS LAN Test'}]);cert.setIssuer(ca.subject.attributes);cert.setExtensions([{name:'basicConstraints',cA:false,critical:true},{name:'keyUsage',digitalSignature:true,keyEncipherment:true,critical:true},{name:'extKeyUsage',serverAuth:true},{name:'subjectAltName',altNames:[{type:2,value:'localhost'},{type:7,ip:'127.0.0.1'},...lanIps.map(ip=>({type:7,ip}))]},{name:'subjectKeyIdentifier'}]);cert.sign(caKeys.privateKey,forge.md.sha256.create());const metadata:LanCertificateMetadata={lanIps,createdAt:now.toISOString(),expiresAt:expires.toISOString()};await mkdir(paths.root,{recursive:true});await Promise.all([writeFile(paths.caPath,forge.pki.certificateToPem(ca)),writeFile(paths.certPath,forge.pki.certificateToPem(cert)),writeFile(paths.keyPath,forge.pki.privateKeyToPem(serverKeys.privateKey),{mode:0o600}),writeFile(paths.metadataPath,JSON.stringify(metadata,null,2))]);return{...paths,...metadata};}
export async function resolveNetworkConfig(appRoot:string,env:NodeJS.ProcessEnv=process.env,interfaces?:Interfaces):Promise<NetworkConfig>{const lanMode=parseLanMode(env.SOREN_LAN_MODE),port=Number(env.SOREN_PORT||8787),lanPort=Number(env.SOREN_LAN_PORT||8788);if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('SOREN_PORT 必须是 1024-65535 之间的整数');if(!Number.isInteger(lanPort)||lanPort<1024||lanPort>65535||lanPort===port)throw new Error('SOREN_LAN_PORT 必须是 1024-65535 之间且不同于 SOREN_PORT 的整数');if(!lanMode){if(env.SOREN_HOST&&!['127.0.0.1','localhost','::1'].includes(env.SOREN_HOST))throw new Error('非 loopback 地址只能在 SOREN_LAN_MODE=true 时使用');const paths=lanPaths(appRoot);return{lanMode:false,host:'127.0.0.1',port,lanHost:null,lanPort:null,protocol:'http',phoneUrl:null,authentication:false,certificate:{ready:false,reason:'LAN Test Mode 未启用',certPath:paths.certPath,keyPath:paths.keyPath,caPath:paths.caPath,lanIps:[]}};}const ips=detectLanIpv4s(interfaces),certificate=await certificateStatus(appRoot,ips);if(!certificate.ready)throw new Error(certificate.reason);return{lanMode:true,host:'127.0.0.1',port,lanHost:'0.0.0.0',lanPort,protocol:'https',phoneUrl:`https://${ips[0]}:${lanPort}`,authentication:false,certificate};}
