import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { LAN_WARNING,certificateStatus,detectLanIpv4s,parseLanMode,resolveNetworkConfig,setupLanCertificate } from './lan.js';

const interfaces=(ip:string)=>({WiFi:[{address:ip,netmask:'255.255.255.0',family:'IPv4' as const,mac:'00:00:00:00:00:00',internal:false,cidr:`${ip}/24`,scopeid:0}]});
test('LAN mode defaults false, preserves localhost, and rejects implicit exposure',async()=>{const root=mkdtempSync(join(tmpdir(),'soren-lan-'));try{assert.equal(parseLanMode(undefined),false);assert.equal(parseLanMode('false'),false);assert.throws(()=>parseLanMode('1'),/true 或 false/);const config=await resolveNetworkConfig(root,{SOREN_PORT:'18787'} as any,interfaces('192.168.1.20'));assert.equal(config.lanMode,false);assert.equal(config.host,'127.0.0.1');assert.equal(config.protocol,'http');await assert.rejects(resolveNetworkConfig(root,{SOREN_HOST:'0.0.0.0'} as any,interfaces('192.168.1.20')),/SOREN_LAN_MODE=true/);}finally{rmSync(root,{recursive:true,force:true});}});
test('explicit LAN mode requires a matching HTTPS certificate and detects IP changes',async()=>{const root=mkdtempSync(join(tmpdir(),'soren-lan-'));try{const missing=await certificateStatus(root,['192.168.1.20']);assert.equal(missing.ready,false);await setupLanCertificate(root,['192.168.1.20']);const ready=await resolveNetworkConfig(root,{SOREN_LAN_MODE:'true',SOREN_PORT:'8787',SOREN_LAN_PORT:'8788'} as any,interfaces('192.168.1.20'));assert.equal(ready.host,'127.0.0.1');assert.equal(ready.lanHost,'0.0.0.0');assert.equal(ready.lanPort,8788);assert.equal(ready.protocol,'https');assert.equal(ready.phoneUrl,'https://192.168.1.20:8788');const changed=await certificateStatus(root,['192.168.1.21']);assert.equal(changed.ready,false);assert.match(changed.reason,/重新运行 pnpm lan:setup/);}finally{rmSync(root,{recursive:true,force:true});}});
test('LAN discovery ignores public and virtual addresses and warning states the security boundary',()=>{assert.deepEqual(detectLanIpv4s({WiFi:[{address:'192.168.50.4',family:'IPv4',internal:false} as any],vEthernet:[{address:'172.20.0.1',family:'IPv4',internal:false} as any],Public:[{address:'8.8.8.8',family:'IPv4',internal:false} as any]}),['192.168.50.4']);assert.match(LAN_WARNING,/ENABLED/);assert.match(LAN_WARNING,/No authentication/);assert.match(LAN_WARNING,/public\/shared Wi-Fi/);});
