import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import type { OmbreMemory } from '@soren/memory';
import { SorenDatabase } from './db.js';
import { MemoryService } from './memory-service.js';

function setup(remote:Partial<OmbreMemory>={}){const directory=mkdtempSync(join(tmpdir(),'soren-memory-')),store=new SorenDatabase(join(directory,'soren.db'));const offline={client:{health:async()=>({configured:true,connected:false})},breath:async()=>{throw new Error('offline')},search:async()=>{throw new Error('offline')},hold:async()=>{throw new Error('offline')},trace:async()=>{throw new Error('offline')},...remote} as unknown as OmbreMemory;return{directory,store,memory:new MemoryService(offline,store)};}

test('recalls a durable fact across conversations while Ombre is offline',async()=>{const{directory,store,memory}=setup();try{await memory.remember({content:'用户喜欢蓝色和海边。',title:'颜色偏好',scope:'long_term',importance:7,sourceType:'chat',sourceId:'chat-a'});const recalled=await memory.recall({message:'你记得我喜欢什么颜色吗？',conversationId:'chat-b',projectId:null});assert.equal(recalled.degraded,true);assert.match(recalled.content,/喜欢蓝色/);assert.equal(store.memory('missing'),null);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('Memory Seed import is idempotent by normalized content',async()=>{const{directory,store,memory}=setup();try{const seed=JSON.stringify({memories:[{title:'称呼',content:'用户喜欢被称作宝宝。',scope:'core',importance:9,pinned:true}]});const first=await memory.importSeed(seed),second=await memory.importSeed(seed);assert.equal(first.imported,1);assert.equal(second.imported,0);assert.equal(second.updated,1);assert.equal(memory.list().length,1);assert.equal(memory.list()[0].pinned,true);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('tracks the Ombre bucket and skips an already synced duplicate',async()=>{let held='',holdCalls=0;const{directory,store,memory}=setup({hold:async(content:string)=>{held=content;holdCalls++;return'新建→bucket_phase2 长期记忆';}});try{const item={content:'跨会话在线记忆',scope:'long_term' as const,sourceType:'chat' as const,sourceId:'chat-a'};const result=await memory.remember(item);await memory.remember(item);assert.equal(held,'跨会话在线记忆');assert.equal(holdCalls,1);assert.equal(result.degraded,false);assert.equal(result.record.syncStatus,'synced');assert.equal(result.record.remoteId,'bucket_phase2');}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

for(const scenario of [
  {name:'long_term to project',from:{scope:'long_term' as const,projectId:null},patch:{scope:'project' as const,projectId:'project-a'},domain:'Workspace:project-a'},
  {name:'project A to project B',from:{scope:'project' as const,projectId:'project-a'},patch:{projectId:'project-b'},domain:'Workspace:project-b'},
  {name:'project to long_term',from:{scope:'project' as const,projectId:'project-a'},patch:{scope:'long_term' as const,projectId:null},domain:'长期记忆'}
])test(`syncs Ombre domain when memory moves ${scenario.name}`,async()=>{let traced:any=null;const{directory,store,memory}=setup({hold:async()=>`新建→bucket_${scenario.name.replaceAll(' ','_')}`,trace:async(id:string,patch:Record<string,unknown>)=>{traced={id,patch};return'updated';}});try{const created=await memory.remember({content:`scope migration ${scenario.name}`,title:'迁移',...scenario.from,sourceType:'manual'});const updated=await memory.update(created.record.id,scenario.patch);assert.equal(updated?.syncStatus,'synced');assert.equal(traced.id,created.record.remoteId);assert.equal(traced.patch.domain,scenario.domain);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('marks local memory failed without losing its scope change when Ombre is offline',async()=>{const{directory,store,memory}=setup({hold:async()=>`新建→bucket_offline`,trace:async()=>{throw new Error('offline');}});try{const created=await memory.remember({content:'离线迁移仍保留',scope:'long_term',sourceType:'manual'}),updated=await memory.update(created.record.id,{scope:'project',projectId:'project-offline'});assert.equal(updated?.scope,'project');assert.equal(updated?.projectId,'project-offline');assert.equal(updated?.syncStatus,'failed');assert.equal(store.memory(created.record.id)?.content,'离线迁移仍保留');}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('recall removes online/local duplicate text and keeps context bounded',async()=>{const large='大'.repeat(15000);const{directory,store,memory}=setup({search:async()=>`远端结果\n重复记忆`,hold:async()=>`新建→bucket_recall`});try{await memory.remember({content:'重复记忆',scope:'long_term',sourceType:'manual'});await memory.remember({content:large,scope:'core',sourceType:'manual'});const result=await memory.recall({message:'重复',conversationId:'chat',projectId:null});assert.equal(result.content.match(/重复记忆/g)?.length,1);assert.ok(result.content.length<=12020);assert.match(result.content,/其余相关记忆已省略/);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('empty recall stays local, archived is excluded, and project scope is isolated',async()=>{let searches=0;const{directory,store,memory}=setup({search:async()=>{searches++;return'remote';}});try{const pinned=await memory.remember({content:'置顶内容',scope:'long_term',pinned:true,sourceType:'manual'}),archived=await memory.remember({content:'归档内容',scope:'long_term',sourceType:'manual'}),project=await memory.remember({content:'项目专属内容',scope:'project',projectId:'project-a',sourceType:'manual'});await memory.update(archived.record.id,{archived:true});const empty=await memory.recall({message:'',conversationId:'chat',projectId:null}),other=await memory.recall({message:'完全无关',conversationId:'chat',projectId:'project-b'}),inside=await memory.recall({message:'项目',conversationId:'chat',projectId:'project-a'});assert.equal(searches,2);assert.match(empty.content,/置顶内容/);assert.doesNotMatch(empty.content,/归档内容/);assert.doesNotMatch(other.content,/项目专属内容/);assert.match(inside.content,/项目专属内容/);assert.equal(store.memory(project.record.id)?.projectId,'project-a');assert.equal(store.memory(pinned.record.id)?.pinned,true);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});
