import type { MemoryRecord, MemoryScope, MemorySeedItem } from '@soren/shared';
import type { OmbreMemory } from '@soren/memory';
import { SorenDatabase, memoryFingerprint } from './db.js';

export interface RecallRequest { message:string; conversationId:string; projectId:string|null; }

function remoteId(text:string){return text.match(/(?:新建|合并|钉选)→([^\s]+)/)?.[1]||null;}
function domainFor(scope:MemoryScope,projectId?:string|null){return scope==='core'?'Soren Core':scope==='project'?`Workspace${projectId?`:${projectId}`:''}`:'长期记忆';}
function contextLimit(text:string,max=12000){return text.length<=max?text:`${text.slice(0,max)}\n\n[其余相关记忆已省略]`;}

export class MemoryService {
  constructor(readonly remote:OmbreMemory,private readonly store:SorenDatabase){}

  async status(){return this.remote.client.health();}
  async surface(){try{return{content:await this.remote.breath(),degraded:false};}catch{return{content:this.render(this.store.relevantMemories('')),degraded:true};}}
  async recall(request:RecallRequest){const local=this.store.relevantMemories(request.message,request.projectId);try{const content=await this.remote.search(request.message,{maxResults:8,automatic:true,withIds:false,domain:''});return{content:contextLimit([content,this.render(local)].filter(Boolean).join('\n\n')),degraded:false,records:local};}catch{return{content:contextLimit(this.render(local)),degraded:true,records:local};}}
  async remember(item:MemorySeedItem&{sourceType:MemoryRecord['sourceType'];sourceId?:string|null}){const result=this.store.upsertMemory(item);if(!result.created&&result.record.syncStatus==='synced')return{record:result.record,created:false,degraded:false,remoteOutput:''};try{const output=await this.remote.hold(result.record.content,{title:result.record.title,domain:domainFor(result.record.scope,result.record.projectId),importance:result.record.importance,pinned:result.record.pinned,whyRemembered:result.record.provenance});return{record:this.store.markMemorySync(result.record.id,'synced',remoteId(output))!,created:result.created,degraded:false,remoteOutput:output};}catch{return{record:this.store.markMemorySync(result.record.id,'failed')!,created:result.created,degraded:true,remoteOutput:''};}}
  list(query=''){return this.store.memories(query);}
  async update(id:string,patch:Partial<Pick<MemoryRecord,'title'|'content'|'scope'|'projectId'|'importance'|'pinned'|'archived'>>){const record=this.store.updateMemory(id,patch);if(!record)return null;if(record.remoteId){try{const remotePatch:Record<string,unknown>={};if('title'in patch)remotePatch.title=record.title;if('content'in patch)remotePatch.content=record.content;if('importance'in patch)remotePatch.importance=record.importance;if('pinned'in patch)remotePatch.pinned=record.pinned?1:0;if(patch.archived)remotePatch.delete=true;await this.remote.trace(record.remoteId,remotePatch);return this.store.markMemorySync(id,'synced');}catch{return this.store.markMemorySync(id,'failed');}}return record;}
  previewSeed(input:unknown){const raw=typeof input==='string'?input:String((input as any)?.content||'');let parsed:any=input;if(typeof input==='string'){try{parsed=JSON.parse(input);}catch{parsed=null;}}let source:any[]=Array.isArray(parsed)?parsed:Array.isArray(parsed?.memories)?parsed.memories:Array.isArray(parsed?.items)?parsed.items:[];if(!source.length&&raw.trim()){source=raw.split(/\n\s*---+\s*\n/g).map(block=>{const lines=block.trim().split('\n');const heading=lines[0]?.match(/^#+\s+(.+)/);return{title:heading?.[1]||'',content:(heading?lines.slice(1):lines).join('\n').trim()};});}const items:MemorySeedItem[]=[],errors:string[]=[];for(const [index,value]of source.slice(0,500).entries()){const content=String(value?.content??value??'').trim();if(!content||content.length>20000){errors.push(`第 ${index+1} 条正文为空或超过 20000 字符`);continue;}const scope=['core','long_term','project','temporary'].includes(value?.scope)?value.scope:'long_term';items.push({title:String(value?.title||'').trim().slice(0,120),content,scope,projectId:value?.projectId||null,importance:Math.max(1,Math.min(10,Number(value?.importance)||5)),pinned:Boolean(value?.pinned),provenance:String(value?.provenance||'Soren Memory Seed').slice(0,500)});}const existing=new Set(this.store.memories('',true).map(item=>item.fingerprint));return{valid:errors.length===0&&items.length>0,items:items.map(item=>({...item,duplicate:existing.has(memoryFingerprint(item.content))})),errors};}
  async importSeed(input:unknown){const preview=this.previewSeed(input);if(!preview.valid)return{...preview,imported:0,updated:0};let imported=0,updated=0,degraded=false;for(const item of preview.items){const result=await this.remember({...item,sourceType:'seed'});result.created?imported++:updated++;degraded||=result.degraded;}return{...preview,imported,updated,degraded};}
  private render(records:MemoryRecord[]){return records.map(item=>`[${item.scope}${item.pinned?' · pinned':''}] ${item.title||'记忆'}\n${item.content}`).join('\n\n');}
}
