import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { SorenDatabase } from './db.js';
import { MomentsService } from './moments-service.js';
import { SocialLifeEngine } from './social-life.js';
import type { SocialGenerationDecision, SocialGenerationRequest, SocialGenerator } from './social-generator.js';

function setup(){const directory=mkdtempSync(join(tmpdir(),'soren-moments-')),file=join(directory,'soren.db'),store=new SorenDatabase(file),moments=new MomentsService(store);return{directory,file,store,moments};}
class FakeGenerator implements SocialGenerator{calls=0;constructor(private decision:(request:SocialGenerationRequest)=>SocialGenerationDecision){}async generate(request:SocialGenerationRequest){this.calls++;return this.decision(request);}}

test('fixed social actors keep identity across restarts',()=>{const{directory,file,store,moments}=setup();try{const kevin=moments.social.actor('kevin');assert.equal(moments.social.actors().length,8);assert.match(kevin!.personality,/损友/);store.db.close();const reopened=new SorenDatabase(file),again=new MomentsService(reopened);assert.equal(again.social.actor('kevin')?.nickname,'Kevin');assert.deepEqual(again.social.actor('kevin')?.memory,kevin?.memory);reopened.db.close();}finally{rmSync(directory,{recursive:true,force:true});}});

test('posts, likes, replies and deletion persist with real timestamps',()=>{const{directory,file,store,moments}=setup();try{const soren=moments.publishActor('soren',{content:'修完一个很隐蔽的 bug。',motivation:'work'}),user=moments.publishUser({content:'今天也在。'});assert.equal(moments.feed().unreadCount,1);assert.equal(moments.read([soren.id]).unreadCount,0);const first=moments.commentUser(soren.id,{content:'辛苦了'}),reply=moments.commentAs(soren.id,'soren','还行。',first.id);moments.likeUser(soren.id);assert.equal(reply.replyToCommentId,first.id);const createdAt=soren.createdAt;moments.deleteUser(user.id);store.db.close();const reopened=new SorenDatabase(file),again=new MomentsService(reopened),post=again.feed().moments.find(item=>item.id===soren.id)!;assert.equal(post.createdAt,createdAt);assert.equal(post.comments.length,2);assert.equal(post.likes.length,1);assert.ok(!again.feed().moments.some(item=>item.id===user.id));reopened.db.close();}finally{rmSync(directory,{recursive:true,force:true});}});

test('NPC can publish and Soren can independently interact through one motivated generation',async()=>{const{directory,store,moments}=setup();const generator=new FakeGenerator(request=>({action:'post',reason:'Kevin 今晚打完一局想吐槽',content:'匹配机制有自己的想法。',interactions:[{type:'like',actorId:'soren'},{type:'comment',actorId:'soren',content:'你也有。'}],statePatch:{currentActivity:'打游戏'}}));try{moments.social.addEvent({type:'npc_life',actorId:'kevin',summary:'Kevin 晚上和朋友打游戏',importance:9,dueAt:new Date(Date.now()-1000).toISOString()});const engine=new SocialLifeEngine(store,moments,generator);await engine.pulse(true);const post=moments.feed().moments[0];assert.equal(generator.calls,1);assert.equal(post.authorId,'kevin');assert.ok(post.likes.some(item=>item.actorId==='soren'));assert.ok(post.comments.some(item=>item.authorId==='soren'));assert.equal(moments.social.state('kevin').currentActivity,'打游戏');}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('a user comment can produce a personality-aware delayed reply without feed reads invoking generation',async()=>{const{directory,store,moments}=setup();const post=moments.publishActor('soren',{content:'随手发一张照片。',imageDescription:'窗边的黑咖啡和摊开的书',motivation:'daily'}),userComment=moments.commentUser(post.id,{content:'今天这么安静？'}),generator=new FakeGenerator(()=>({action:'interact',reason:'回应用户',targetMomentId:post.id,replyToCommentId:userComment.id,content:'只是没把每句话都说出来。'})),engine=new SocialLifeEngine(store,moments,generator);try{moments.feed();moments.feed();assert.equal(generator.calls,0);moments.social.addEvent({type:'user_comment',actorId:'soren',targetId:post.id,summary:'用户追问今天为什么安静',importance:9,dueAt:new Date(Date.now()-1000).toISOString(),metadata:{commentId:userComment.id}});await engine.pulse(true);const updated=moments.social.post(post.id)!;assert.equal(generator.calls,1);assert.ok(updated.comments.some(item=>item.authorId==='soren'&&item.replyToCommentId===userComment.id));}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('publishing a user moment schedules a delayed Soren reaction without feed reads invoking generation',()=>{const{directory,store,moments}=setup();try{const post=moments.publishUser({content:'今天开放朋友圈权限。'});moments.feed();moments.feed();const event=store.db.prepare("SELECT type,actor_id,target_id,due_at,consumed_at FROM social_events WHERE type='user_post'").get() as any;assert.equal(event.actor_id,'soren');assert.equal(event.target_id,post.id);assert.equal(event.consumed_at,null);assert.ok(Date.parse(event.due_at)>Date.now());assert.equal(store.setting('momentsNextEvaluationAt',''),event.due_at);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('recent user moments missed by an older build are reconciled once',()=>{const{directory,store,moments}=setup();try{const post=moments.publishUser({content:'这条动态来自旧版本。'});store.db.prepare("DELETE FROM social_events WHERE type='user_post'").run();new MomentsService(store);new MomentsService(store);const events=store.db.prepare("SELECT target_id FROM social_events WHERE type='user_post'").all() as any[];assert.deepEqual(events.map(item=>item.target_id),[post.id]);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('replying to Soren under the user own post schedules Soren instead of the post author',()=>{const{directory,store,moments}=setup();try{const post=moments.publishUser({content:'终于开放朋友圈。'}),sorenComment=moments.commentAs(post.id,'soren','先别急。'),reply=moments.commentUser(post.id,{content:'为什么？',replyToCommentId:sorenComment.id}),event=store.db.prepare("SELECT actor_id,target_id,metadata_json FROM social_events WHERE type='user_comment'").get() as any;assert.equal(event.actor_id,'soren');assert.equal(event.target_id,post.id);assert.equal(JSON.parse(event.metadata_json).commentId,reply.id);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});

test('daily cap and duplicate protection prevent robotic flooding',async()=>{const{directory,store,moments}=setup();try{for(let index=0;index<4;index++)moments.publishActor(index%2?'kevin':'soren',{content:`自然活动 ${index}`,motivation:'life-engine'});assert.throws(()=>moments.publishActor('soren',{content:'自然活动 0',motivation:'life-engine'}),/已经发过/);const generator=new FakeGenerator(()=>({action:'post',reason:'不应执行',content:'第五条'})),engine=new SocialLifeEngine(store,moments,generator);await engine.pulse(true);assert.equal(generator.calls,0);assert.equal(engine.status().generatedToday,4);assert.match(engine.status().lastOutcome,/上限/);}finally{store.db.close();rmSync(directory,{recursive:true,force:true});}});
