import type { NotificationRecord,PushDeliveryStatus,PushSubscriptionRecord } from '@soren/shared';
import type { SorenDatabase } from './db.js';
import type { SystemDeliverySink } from './event-service.js';
import type { SystemNotificationPayload,SystemNotificationProvider } from './system-notification-provider.js';

const now=()=>new Date().toISOString();
const clean=(value:unknown,max:number)=>String(value||'').trim().slice(0,max);
const publicSubscription=(row:any):PushSubscriptionRecord=>({id:row.id,endpoint:'',deviceLabel:row.device_label,createdAt:row.created_at,updatedAt:row.updated_at,lastSuccessAt:row.last_success_at,failureCount:Number(row.failure_count)||0,disabledAt:row.disabled_at});

export class PushDeliveryService implements SystemDeliverySink{
  private timer:NodeJS.Timeout|null=null;private running=false;readonly maxAttempts=3;
  constructor(private readonly db:SorenDatabase,readonly provider:SystemNotificationProvider,private readonly clock:()=>Date=()=>new Date(),private readonly autoDeliver=true){}
  start(){if(this.timer)return;this.timer=setInterval(()=>void this.pulse(),30_000);this.timer.unref();void this.pulse();}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
  status(input:{supported?:boolean;permission?:string;subscriptionId?:string}={}){const id=clean(input.subscriptionId,100),row=id?this.db.db.prepare('SELECT * FROM push_subscriptions WHERE id=? AND disabled_at IS NULL').get(id) as any:null;return{browserSupported:Boolean(input.supported),permission:clean(input.permission,20)||'unknown',serverConfigured:this.provider.configured(),publicKey:this.provider.publicKey(),subscribed:Boolean(row),subscription:row?publicSubscription(row):null,activeDevices:Number((this.db.db.prepare('SELECT COUNT(*) count FROM push_subscriptions WHERE disabled_at IS NULL').get() as any).count)};}
  subscribe(input:any){if(!this.provider.configured())throw new Error('Web Push 尚未配置 VAPID');const endpoint=clean(input?.endpoint,4096),p256dh=clean(input?.keys?.p256dh,1024),auth=clean(input?.keys?.auth,512),label=clean(input?.deviceLabel,80)||'此设备';if(!/^https:\/\//.test(endpoint)||!p256dh||!auth)throw new Error('无效 Push subscription');const at=now(),existing=this.db.db.prepare('SELECT id,created_at FROM push_subscriptions WHERE endpoint=?').get(endpoint) as any,id=existing?.id||crypto.randomUUID();this.db.db.prepare(`INSERT INTO push_subscriptions (id,endpoint,p256dh,auth,device_label,created_at,updated_at,last_success_at,failure_count,disabled_at) VALUES (?,?,?,?,?,?,?,?,?,NULL) ON CONFLICT(endpoint) DO UPDATE SET p256dh=excluded.p256dh,auth=excluded.auth,device_label=excluded.device_label,updated_at=excluded.updated_at,failure_count=0,disabled_at=NULL`).run(id,endpoint,p256dh,auth,label,existing?.created_at||at,at,null,0);this.enqueuePendingFor(id);return publicSubscription(this.db.db.prepare('SELECT * FROM push_subscriptions WHERE id=?').get(id));}
  unsubscribe(id:string){const result=this.db.db.prepare('UPDATE push_subscriptions SET disabled_at=?,updated_at=? WHERE id=? AND disabled_at IS NULL').run(now(),now(),id);this.db.db.prepare("UPDATE push_deliveries SET status='suppressed',updated_at=?,next_attempt_at=NULL WHERE subscription_id=? AND status IN ('pending','failed')").run(now(),id);return result.changes>0;}
  enqueue(notification:NotificationRecord){if(notification.deliveryChannel!=='system'||notification.status!=='pending')return;const subscriptions=this.db.db.prepare('SELECT id FROM push_subscriptions WHERE disabled_at IS NULL').all() as any[],at=now(),insert=this.db.db.prepare(`INSERT OR IGNORE INTO push_deliveries (id,notification_id,subscription_id,provider,status,attempt_count,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)`);this.db.db.transaction(()=>{for(const subscription of subscriptions)insert.run(crypto.randomUUID(),notification.id,subscription.id,this.provider.id,'pending',0,at,at);})();if(subscriptions.length&&this.autoDeliver)void this.pulse();}
  async pulse(force=false){if(this.running||!this.provider.configured())return;this.running=true;try{const due=this.db.db.prepare(`SELECT delivery.*,subscription.endpoint,subscription.p256dh,subscription.auth,notification.type,notification.body,notification.conversation_id,notification.message_id,notification.created_at notification_created_at FROM push_deliveries delivery JOIN push_subscriptions subscription ON subscription.id=delivery.subscription_id JOIN notifications notification ON notification.id=delivery.notification_id WHERE subscription.disabled_at IS NULL AND delivery.status IN ('pending','failed') AND delivery.attempt_count<? AND (?=1 OR delivery.next_attempt_at IS NULL OR delivery.next_attempt_at<=?) ORDER BY delivery.created_at LIMIT 20`).all(this.maxAttempts,force?1:0,this.clock().toISOString()) as any[];for(const row of due)await this.deliver(row);}finally{this.running=false;}}
  deliveries(notificationId?:string){const rows=(notificationId?this.db.db.prepare('SELECT * FROM push_deliveries WHERE notification_id=? ORDER BY created_at').all(notificationId):this.db.db.prepare('SELECT * FROM push_deliveries ORDER BY created_at').all()) as any[];return rows.map(row=>({id:row.id,notificationId:row.notification_id,subscriptionId:row.subscription_id,provider:row.provider,status:row.status as PushDeliveryStatus,attemptCount:row.attempt_count,lastErrorCode:row.last_error_code,nextAttemptAt:row.next_attempt_at,sentAt:row.sent_at}));}
  private enqueuePendingFor(subscriptionId:string){const rows=this.db.db.prepare("SELECT id FROM notifications WHERE delivery_channel='system' AND status='pending'").all() as any[],at=now(),insert=this.db.db.prepare(`INSERT OR IGNORE INTO push_deliveries (id,notification_id,subscription_id,provider,status,attempt_count,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)`);this.db.db.transaction(()=>{for(const row of rows)insert.run(crypto.randomUUID(),row.id,subscriptionId,this.provider.id,'pending',0,at,at);})();}
  private async deliver(row:any){const payload:SystemNotificationPayload={notificationId:row.notification_id,type:row.type,title:'Soren',body:clean(row.body,220),conversationId:row.conversation_id||null,messageId:row.message_id||null,deepLink:row.conversation_id?`/?view=chat&conversation=${encodeURIComponent(row.conversation_id)}${row.message_id?`&message=${encodeURIComponent(row.message_id)}`:''}`:'/',createdAt:row.notification_created_at},result=await this.provider.send({endpoint:row.endpoint,p256dh:row.p256dh,auth:row.auth},payload),at=this.clock().toISOString(),attempt=Number(row.attempt_count)+1;if(result.status==='sent'){this.db.db.transaction(()=>{this.db.db.prepare("UPDATE push_deliveries SET status='sent',attempt_count=?,last_error_code=NULL,next_attempt_at=NULL,updated_at=?,sent_at=? WHERE id=?").run(attempt,at,at,row.id);this.db.db.prepare('UPDATE push_subscriptions SET last_success_at=?,failure_count=0,updated_at=? WHERE id=?').run(at,at,row.subscription_id);this.db.db.prepare("UPDATE notifications SET status='delivered',delivered_at=COALESCE(delivered_at,?) WHERE id=? AND status='pending'").run(at,row.notification_id);})();return;}if(result.status==='invalid_subscription'){this.db.db.transaction(()=>{this.db.db.prepare("UPDATE push_deliveries SET status='invalid_subscription',attempt_count=?,last_error_code=?,next_attempt_at=NULL,updated_at=? WHERE id=?").run(attempt,result.errorCode||'invalid_subscription',at,row.id);this.db.db.prepare('UPDATE push_subscriptions SET disabled_at=?,updated_at=?,failure_count=failure_count+1 WHERE id=?').run(at,at,row.subscription_id);})();return;}const next=attempt>=this.maxAttempts?null:new Date(this.clock().getTime()+attempt*60_000).toISOString();this.db.db.transaction(()=>{this.db.db.prepare("UPDATE push_deliveries SET status='failed',attempt_count=?,last_error_code=?,next_attempt_at=?,updated_at=? WHERE id=?").run(attempt,result.errorCode||'temporary_failure',next,at,row.id);this.db.db.prepare('UPDATE push_subscriptions SET failure_count=failure_count+1,updated_at=? WHERE id=?').run(at,row.subscription_id);})();}
}
