import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { SorenDatabase } from './db.js';
import { EventService } from './event-service.js';
import { PushDeliveryService } from './push-delivery-service.js';
import { WebPushNotificationProvider } from './web-push-provider.js';
import webpush from 'web-push';
import type { DeliveryResult,SystemNotificationPayload,SystemNotificationProvider } from './system-notification-provider.js';
import { ReminderService } from './reminder-service.js';

class FakeProvider implements SystemNotificationProvider{readonly id='fake';results:DeliveryResult[]=[];sent:SystemNotificationPayload[]=[];configured(){return true;}publicKey(){return 'public-key';}async send(_subscription:any,payload:SystemNotificationPayload){this.sent.push(payload);return this.results.shift()||{status:'sent'} as DeliveryResult;}}
const subscription=(suffix:string)=>({endpoint:`https://push.example.test/${suffix}`,keys:{p256dh:`key-${suffix}`,auth:`auth-${suffix}`},deviceLabel:`设备 ${suffix}`});
function setup(file?:string){const directory=file?'':mkdtempSync(join(tmpdir(),'soren-push-')),path=file||join(directory,'soren.db'),db=new SorenDatabase(path),provider=new FakeProvider(),push=new PushDeliveryService(db,provider,()=>new Date('2026-09-17T12:00:00.000Z'),false),events=new EventService(db,push);db.setSetting('systemNotificationsEnabled',true);return{directory,path,db,provider,push,events};}

test('reports missing VAPID config without attempting delivery',async()=>{const provider=new WebPushNotificationProvider({publicKey:'',privateKey:'',subject:''});assert.equal(provider.configured(),false);assert.equal(provider.publicKey(),'');assert.deepEqual(await provider.send({endpoint:'https://push.example.test/missing',p256dh:'key',auth:'auth'},{notificationId:'n',type:'push.test',title:'Soren',body:'test',conversationId:null,messageId:null,deepLink:'/',createdAt:'2026-09-17T12:00:00.000Z'}),{status:'temporary_failure',errorCode:'vapid_not_configured'});});

test('uses the configured HTTPS proxy for Web Push delivery',async()=>{const original=webpush.sendNotification,keys=webpush.generateVAPIDKeys();let options:any;webpush.sendNotification=(async(_subscription:any,_payload:any,value:any)=>{options=value;return{} as any;}) as any;try{const provider=new WebPushNotificationProvider({publicKey:keys.publicKey,privateKey:keys.privateKey,subject:'mailto:test@example.com',proxy:'http://127.0.0.1:7892'});const result=await provider.send({endpoint:'https://push.example.test/proxy',p256dh:'key',auth:'auth'},{notificationId:'n',type:'push.test',title:'Soren',body:'test',conversationId:null,messageId:null,deepLink:'/',createdAt:'2026-09-17T12:00:00.000Z'});assert.equal(result.status,'sent');assert.equal(options.proxy,'http://127.0.0.1:7892');assert.equal(options.timeout,15_000);}finally{webpush.sendNotification=original;}});

test('persists subscriptions, fans out once, and carries a Chat deep link',async()=>{const state=setup();try{state.push.subscribe(subscription('phone'));state.push.subscribe(subscription('tablet'));const result=state.events.emit({type:'assistant.proactive_message',sourceType:'soren',sourceId:'hello',body:'回来看看我。'}),system=result.notifications.find(item=>item.deliveryChannel==='system')!;assert.equal(state.push.deliveries(system.id).length,2);state.events.emit({type:'assistant.proactive_message',sourceType:'soren',sourceId:'hello',body:'回来看看我。'});assert.equal(state.push.deliveries(system.id).length,2);await state.push.pulse(true);assert.equal(state.provider.sent.length,2);assert.ok(state.provider.sent.every(item=>item.title==='Soren'&&item.deepLink.includes(`conversation=${encodeURIComponent(system.conversationId!)}`)&&item.messageId));assert.equal(state.push.deliveries(system.id).filter(item=>item.status==='sent').length,2);assert.equal(state.events.notifications({channel:'system'})[0].status,'pending');state.push.acknowledge({notificationId:system.id,stage:'notification_displayed'});assert.equal(state.events.notifications({channel:'system'})[0].status,'delivered');}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('does not enqueue Home or Moments and suppresses system delivery when disabled',()=>{const state=setup();try{state.push.subscribe(subscription('phone'));state.events.emit({type:'home_note.created',sourceType:'home',sourceId:'h',body:'Home'});state.events.emit({type:'moment.created',sourceType:'moment',sourceId:'m',body:'Moment'});state.db.setSetting('systemNotificationsEnabled',false);const result=state.events.emit({type:'cyberdaddy.followup_due',sourceType:'cyberdaddy',sourceId:'c',body:'去睡觉'});assert.equal(state.push.deliveries().length,0);assert.equal(result.notifications.find(item=>item.deliveryChannel==='system')?.status,'suppressed');}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('user Moments, comments, and likes remain in-app-only',()=>{const state=setup();try{state.push.subscribe(subscription('phone'));for(const [type,id] of [['moment.created','user-moment'],['moment.comment.created','comment'],['moment.like.created','like']])state.events.emit({type,sourceType:'user',sourceId:id,body:id});assert.equal(state.push.deliveries().length,0);assert.ok(state.events.notifications().every(item=>item.deliveryChannel==='in_app'));}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('retries temporary failures and disables expired subscriptions',async()=>{const state=setup();try{const first=state.push.subscribe(subscription('phone'));state.provider.results.push({status:'temporary_failure',errorCode:'503'});const one=state.events.emit({type:'push.test',sourceType:'user',sourceId:'one',body:'one'}).notifications[0];await state.push.pulse(true);assert.equal(state.push.deliveries(one.id)[0].attemptCount,1);assert.equal(state.push.deliveries(one.id)[0].status,'failed');state.provider.results.push({status:'invalid_subscription',errorCode:'410'});await state.push.pulse(true);assert.equal(state.push.status({subscriptionId:first.id}).subscribed,false);assert.equal(state.push.deliveries(one.id)[0].status,'invalid_subscription');}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('pending queue survives a clean shutdown and unsubscribe removes future work',()=>{const state=setup();const saved=state.push.subscribe(subscription('phone'));state.events.emit({type:'push.test',sourceType:'user',sourceId:'persisted',body:'保留'});assert.equal(state.push.deliveries().length,1);state.push.stop();state.db.close();const reopened=setup(state.path);try{assert.equal(reopened.push.deliveries().length,1);assert.equal(reopened.push.unsubscribe(saved.id),true);assert.equal(reopened.push.status({subscriptionId:saved.id}).subscribed,false);assert.equal(reopened.push.deliveries()[0].status,'suppressed');}finally{reopened.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('due Simple Reminder creates exactly one Chat, system notification, queue item and provider attempt',async()=>{const directory=mkdtempSync(join(tmpdir(),'soren-reminder-push-')),file=join(directory,'soren.db');let current=new Date('2026-09-18T03:00:00.000Z');try{const db=new SorenDatabase(file),provider=new FakeProvider(),push=new PushDeliveryService(db,provider,()=>new Date(current),false),events=new EventService(db,push),reminders=new ReminderService(db,events,()=>new Date(current)),conversation=db.createConversation('真机');db.setSetting('systemNotificationsEnabled',true);push.subscribe(subscription('android'));const reminder=reminders.create({title:'检查提醒',remindAt:'2026-09-18T03:02:00.000Z',timezone:'Asia/Shanghai',sourceConversationId:conversation.id,idempotencyKey:'integrated'});current=new Date('2026-09-18T03:02:01.000Z');await reminders.pulse();await reminders.pulse();const system=events.notifications({channel:'system'}).find(item=>item.sourceId===reminder.id)!;assert.equal(db.messages(conversation.id).filter(item=>item.role==='assistant').length,1);assert.equal(system.type,'reminder.due');assert.equal(push.deliveries(system.id).length,1);await push.pulse(true);await push.pulse(true);assert.equal(provider.sent.length,1);assert.equal(provider.sent[0].type,'reminder.due');assert.equal(provider.sent[0].messageId,db.messages(conversation.id).at(-1)?.id);assert.equal(push.deliveries(system.id)[0].status,'sent');db.close();const reopenedDb=new SorenDatabase(file),reopenedProvider=new FakeProvider(),reopenedPush=new PushDeliveryService(reopenedDb,reopenedProvider,()=>new Date('2026-09-18T03:05:00.000Z'),false),reopenedEvents=new EventService(reopenedDb,reopenedPush),reopenedReminders=new ReminderService(reopenedDb,reopenedEvents,()=>new Date('2026-09-18T03:05:00.000Z'));await reopenedReminders.pulse();await reopenedPush.pulse(true);assert.equal(reopenedProvider.sent.length,0);assert.equal(reopenedEvents.events().filter(item=>item.type==='reminder.due'&&item.sourceId===reminder.id).length,1);reopenedDb.close();}finally{rmSync(directory,{recursive:true,force:true});}});

test('cancelled Reminder and disabled system notifications preserve policy boundaries',async()=>{const state=setup();try{state.push.subscribe(subscription('android'));let current=new Date('2026-09-18T03:00:00.000Z');const reminders=new ReminderService(state.db,state.events,()=>new Date(current)),cancelled=reminders.create({title:'不要触发',remindAt:'2026-09-18T03:01:00.000Z',timezone:'Asia/Shanghai',idempotencyKey:'cancelled'});reminders.cancel(cancelled.id);current=new Date('2026-09-18T03:02:00.000Z');await reminders.pulse();assert.equal(state.provider.sent.length,0);assert.equal(state.push.deliveries().length,0);state.db.setSetting('systemNotificationsEnabled',false);const active=reminders.create({title:'只进 Chat',remindAt:'2026-09-18T03:03:00.000Z',timezone:'Asia/Shanghai',idempotencyKey:'disabled'});current=new Date('2026-09-18T03:04:00.000Z');await reminders.pulse();const system=state.events.notifications({channel:'system'}).find(item=>item.sourceId===active.id)!;assert.equal(system.status,'suppressed');assert.equal(state.events.notifications({channel:'chat'}).find(item=>item.sourceId===active.id)?.status,'delivered');assert.equal(state.push.deliveries(system.id).length,0);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('device receipts distinguish provider acceptance from Android display',async()=>{const state=setup();try{state.push.subscribe(subscription('android'));const system=state.events.emit({type:'push.test',sourceType:'user',sourceId:'receipt',body:'receipt'}).notifications.find(item=>item.deliveryChannel==='system')!;await state.push.pulse(true);let diagnostic=state.push.diagnostics().find(item=>item.notificationId===system.id)!;assert.equal(diagnostic.deliveryState,'sent');assert.equal(diagnostic.deviceReceivedAt,null);assert.equal(diagnostic.displayedAt,null);assert.equal(state.push.acknowledge({notificationId:system.id,stage:'push_received'}),true);assert.equal(state.push.acknowledge({notificationId:system.id,stage:'notification_displayed'}),true);diagnostic=state.push.diagnostics().find(item=>item.notificationId===system.id)!;assert.ok(diagnostic.deviceReceivedAt);assert.ok(diagnostic.displayedAt);assert.equal(diagnostic.safeErrorCode,null);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});
