import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { SorenDatabase } from './db.js';
import { EventService } from './event-service.js';
import { ReminderService } from './reminder-service.js';

function setup(initial='2026-09-17T13:55:00.000Z',system=false){const directory=mkdtempSync(join(tmpdir(),'soren-reminders-')),file=join(directory,'soren.db'),db=new SorenDatabase(file),queued:any[]=[];db.setSetting('systemNotificationsEnabled',system);let current=new Date(initial);const events=new EventService(db,{enqueue:item=>queued.push(item)}),service=new ReminderService(db,events,()=>new Date(current));return{directory,file,db,events,service,queued,setTime:(value:string)=>{current=new Date(value);}};}

test('persists a Chat reminder with source and survives Core restart',()=>{const state=setup();try{const conversation=state.db.createConversation('真机测试'),message=state.db.addMessage(conversation.id,'user','2分钟后提醒我喝水'),created=state.service.create({title:'喝水',remindAt:'2026-09-17T13:57:00.000Z',timezone:'Asia/Shanghai',sourceConversationId:conversation.id,sourceMessageId:message.id,idempotencyKey:'chat-message-1'});assert.equal(created.status,'scheduled');assert.equal(created.sourceConversationId,conversation.id);assert.equal(state.events.events()[0].type,'reminder.created');state.db.close();const reopenedDb=new SorenDatabase(state.file),reopened=new ReminderService(reopenedDb,new EventService(reopenedDb));assert.equal(reopened.get(created.id)?.title,'喝水');assert.equal(reopened.get(created.id)?.remindAt,'2026-09-17T13:57:00.000Z');reopenedDb.close();}finally{rmSync(state.directory,{recursive:true,force:true});}});

test('fires once into proactive Soren Chat and creates a system-push eligible notification',async()=>{const state=setup('2026-09-17T13:55:00.000Z',true);try{const conversation=state.db.createConversation('日常'),reminder=state.service.create({title:'看看有没生效',remindAt:'2026-09-17T13:57:00.000Z',timezone:'Asia/Shanghai',sourceConversationId:conversation.id,idempotencyKey:'once'});state.setTime('2026-09-17T13:57:01.000Z');await state.service.pulse();await state.service.pulse();assert.equal(state.service.get(reminder.id)?.status,'fired');assert.equal(state.events.events().filter(item=>item.type==='reminder.due').length,1);assert.equal(state.db.messages(conversation.id).filter(item=>item.role==='assistant').length,1);const system=state.events.notifications({channel:'system'}).find(item=>item.sourceId===reminder.id)!;assert.equal(system.status,'pending');assert.equal(state.queued.length,1);assert.equal(system.body,'到时间了：看看有没生效');}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('disabled system notifications still create Chat delivery',async()=>{const state=setup();try{const reminder=state.service.create({title:'关电脑',remindAt:'2026-09-17T13:56:00.000Z',timezone:'Asia/Shanghai',idempotencyKey:'no-system'});state.setTime('2026-09-17T13:56:01.000Z');await state.service.pulse();const notices=state.events.notifications().filter(item=>item.sourceId===reminder.id&&item.type==='reminder.due');assert.equal(notices.find(item=>item.deliveryChannel==='chat')?.status,'delivered');assert.equal(notices.find(item=>item.deliveryChannel==='system')?.status,'suppressed');assert.equal(state.queued.length,0);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('cancelled reminder never fires and duplicate idempotency key never duplicates',async()=>{const state=setup();try{const input={title:'关火',remindAt:'2026-09-17T13:56:00.000Z',timezone:'Asia/Shanghai',idempotencyKey:'same'},first=state.service.create(input),second=state.service.create(input);assert.equal(second.id,first.id);assert.equal(state.service.list().length,1);state.service.cancel(first.id);state.setTime('2026-09-17T14:00:00.000Z');await state.service.pulse();assert.equal(state.service.get(first.id)?.status,'cancelled');assert.equal(state.events.events().filter(item=>item.type==='reminder.due').length,0);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('archived and missing source conversations use a safe proactive fallback',async()=>{const state=setup();try{const archived=state.db.createConversation('归档');state.db.updateConversation(archived.id,{archived:true});state.service.create({title:'归档来源',remindAt:'2026-09-17T13:56:00.000Z',timezone:'Asia/Shanghai',sourceConversationId:archived.id,idempotencyKey:'archived'});state.service.create({title:'缺失来源',remindAt:'2026-09-17T13:56:00.000Z',timezone:'Asia/Shanghai',sourceConversationId:'missing',idempotencyKey:'missing'});state.setTime('2026-09-17T13:56:01.000Z');await state.service.pulse();const chat=state.events.notifications({channel:'chat'}).filter(item=>item.type==='reminder.due');assert.equal(chat.length,2);assert.ok(chat.every(item=>item.conversationId!==archived.id));assert.equal(chat[0].conversationId,chat[1].conversationId);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});
