import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { SorenDatabase } from './db.js';
import { EventService } from './event-service.js';
import { ReminderService } from './reminder-service.js';
import { CyberDaddyService } from './cyberdaddy-service.js';
import { ACTION_CLOSE,ACTION_OPEN,looksLikeSchedulingRequest,parseScheduleActions,ScheduleActionService,zonedLocalToUtc } from './schedule-actions.js';

function setup(){const directory=mkdtempSync(join(tmpdir(),'soren-actions-')),db=new SorenDatabase(join(directory,'soren.db')),events=new EventService(db),clock=()=>new Date('2026-09-17T13:55:00.000Z'),reminders=new ReminderService(db,events,clock),cyberDaddy=new CyberDaddyService(db,events,clock),actions=new ScheduleActionService(db,reminders,cyberDaddy,clock),conversation=db.createConversation('调度测试'),message=db.addMessage(conversation.id,'user','2分钟后提醒我');return{directory,db,events,reminders,cyberDaddy,actions,conversation,message};}

test('Chat scheduling intent is routed to a structured action instead of regex creation',()=>{assert.equal(looksLikeSchedulingRequest('2分钟后提醒我喝水'),true);const parsed=parseScheduleActions(`${ACTION_OPEN}{"actions":[{"type":"create_reminder","title":"喝水","delayMinutes":2,"timezone":"Asia/Shanghai"}]}${ACTION_CLOSE}`);assert.deepEqual(parsed,[{type:'create_reminder',title:'喝水',delayMinutes:2,timezone:'Asia/Shanghai'}]);assert.deepEqual(parseScheduleActions('好，我会提醒你。'),[]);});

test('structured create_reminder uses Core time, persists, appears in Timeline data, and makes no commitment',()=>{const state=setup();try{const reply=state.actions.execute([{type:'create_reminder',title:'看看有没生效',delayMinutes:2,timezone:'Asia/Shanghai'}],{conversationId:state.conversation.id,messageId:state.message.id,turnId:'turn-1'}),item=state.reminders.list()[0];assert.match(reply,/21:57/);assert.equal(item.remindAt,'2026-09-17T13:57:00.000Z');assert.equal(state.actions.scheduledItems()[0].type,'reminder');assert.equal(state.cyberDaddy.commitments().length,0);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('duplicate structured tool call is idempotent across retry',()=>{const state=setup();try{const action={type:'create_reminder' as const,title:'喝水',delayMinutes:2,timezone:'Asia/Shanghai'};state.actions.execute([action,action],{conversationId:state.conversation.id,messageId:state.message.id,turnId:'turn-a'});state.actions.execute([action],{conversationId:state.conversation.id,messageId:state.message.id,turnId:'turn-b'});assert.equal(state.reminders.list().length,1);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('explicit supervision creates a CyberDaddy commitment and preserves recurring semantics',()=>{const state=setup();try{state.actions.execute([{type:'create_commitment',description:'每天晚上11点前睡觉',domainId:'sleep',recurrence:'daily',recurrenceTime:'23:00',timezone:'Asia/Shanghai'}],{conversationId:state.conversation.id,messageId:state.message.id,turnId:'turn-c'});const commitment=state.cyberDaddy.commitments()[0];assert.equal(commitment.recurrence,'daily');assert.equal(commitment.recurrenceTime,'23:00');assert.equal(commitment.sourceConversationId,state.conversation.id);assert.equal(state.cyberDaddy.snapshot().enabled,true);assert.equal(state.cyberDaddy.snapshot().domains.find(item=>item.id==='sleep')?.enabled,true);assert.equal(state.reminders.list().length,0);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('relative and absolute time honor Asia/Shanghai while ambiguous time requests clarification',()=>{const state=setup();try{assert.equal(zonedLocalToUtc('2026-09-18T08:00:00','Asia/Shanghai').toISOString(),'2026-09-18T00:00:00.000Z');const reply=state.actions.execute([{type:'request_clarification',question:'你想让我明天几点提醒？'}],{conversationId:state.conversation.id,messageId:state.message.id,turnId:'turn-d'});assert.equal(reply,'你想让我明天几点提醒？');assert.equal(state.reminders.list().length,0);assert.throws(()=>state.actions.execute([{type:'create_reminder',title:'明天提醒',timezone:'Asia/Shanghai'}],{conversationId:state.conversation.id,messageId:state.message.id,turnId:'turn-e'}),/时间不明确/);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});

test('persistence failure prevents a successful confirmation',()=>{const state=setup();try{const broken=new ScheduleActionService(state.db,{...state.reminders,create:()=>{throw new Error('disk full');}} as any,state.cyberDaddy,()=>new Date('2026-09-17T13:55:00.000Z'));assert.throws(()=>broken.execute([{type:'create_reminder',title:'喝水',delayMinutes:2,timezone:'Asia/Shanghai'}],{conversationId:state.conversation.id,messageId:state.message.id,turnId:'turn-f'}),/disk full/);}finally{state.db.close();rmSync(state.directory,{recursive:true,force:true});}});
