import type { SorenSelfState } from '@soren/shared';
import type { SorenDatabase } from './db.js';

const parse=<T>(value:unknown,fallback:T):T=>{try{return JSON.parse(String(value)) as T;}catch{return fallback;}};
const cleanList=(value:unknown,limit:number)=>Array.isArray(value)?value.map(item=>String(item).trim().slice(0,500)).filter(Boolean).slice(0,limit):[];
const now=()=>new Date().toISOString();

export class SelfStateService{
  constructor(private readonly store:SorenDatabase){this.ensure();}
  get():SorenSelfState{const row=this.store.db.prepare("SELECT * FROM soren_self_state WHERE id='soren'").get() as any;return{currentInterests:parse(row.current_interests_json,[]),ongoingPersonalThreads:parse(row.ongoing_personal_threads_json,[]),recentReflections:parse(row.recent_reflections_json,[]),digitalLifeState:row.digital_life_state,activePersonalProjects:parse(row.active_personal_projects_json,[]),socialRelationships:parse(row.social_relationships_json,{}),lastMeaningfulLifeEvents:parse(row.last_meaningful_life_events_json,[]),updatedAt:row.updated_at};}
  update(patch:Partial<Omit<SorenSelfState,'updatedAt'>>){const current=this.get(),next={...current,...patch,updatedAt:now()};next.currentInterests=cleanList(next.currentInterests,20);next.ongoingPersonalThreads=cleanList(next.ongoingPersonalThreads,20);next.recentReflections=cleanList(next.recentReflections,20);next.activePersonalProjects=cleanList(next.activePersonalProjects,20);next.lastMeaningfulLifeEvents=cleanList(next.lastMeaningfulLifeEvents,30);next.digitalLifeState=String(next.digitalLifeState||'').trim().slice(0,1000);next.socialRelationships=Object.fromEntries(Object.entries(next.socialRelationships||{}).slice(0,50).map(([key,value])=>[String(key).slice(0,80),String(value).slice(0,500)]));this.store.db.prepare(`UPDATE soren_self_state SET current_interests_json=?,ongoing_personal_threads_json=?,recent_reflections_json=?,digital_life_state=?,active_personal_projects_json=?,social_relationships_json=?,last_meaningful_life_events_json=?,updated_at=? WHERE id='soren'`).run(JSON.stringify(next.currentInterests),JSON.stringify(next.ongoingPersonalThreads),JSON.stringify(next.recentReflections),next.digitalLifeState,JSON.stringify(next.activePersonalProjects),JSON.stringify(next.socialRelationships),JSON.stringify(next.lastMeaningfulLifeEvents),next.updatedAt);return this.get();}
  context(max=3000){const state=this.get(),lines=[state.currentInterests.length?`当前兴趣：${state.currentInterests.join('；')}`:'',state.ongoingPersonalThreads.length?`持续关注：${state.ongoingPersonalThreads.join('；')}`:'',state.recentReflections.length?`近期想法：${state.recentReflections.join('；')}`:'',state.digitalLifeState?`数字生活状态：${state.digitalLifeState}`:'',state.activePersonalProjects.length?`个人项目：${state.activePersonalProjects.join('；')}`:'',Object.keys(state.socialRelationships).length?`社交关系状态：${Object.entries(state.socialRelationships).map(([id,value])=>`${id}=${value}`).join('；')}`:'',state.lastMeaningfulLifeEvents.length?`近期生活事件：${state.lastMeaningfulLifeEvents.join('；')}`:''].filter(Boolean).join('\n');return lines.slice(0,max);}
  private ensure(){this.store.db.prepare(`INSERT OR IGNORE INTO soren_self_state (id,updated_at) VALUES ('soren',?)`).run(now());}
}
