import { createHash } from 'node:crypto';
import type { MomentComment, MomentLike, MomentMedia, MomentPost, SocialActor } from '@soren/shared';
import type { SorenDatabase } from './db.js';

const now=()=>new Date().toISOString();
const bool=(value:unknown)=>Boolean(Number(value));
const parse=<T>(value:unknown,fallback:T):T=>{try{return JSON.parse(String(value)) as T;}catch{return fallback;}};
const fingerprint=(value:string)=>createHash('sha256').update(value.trim().replace(/\s+/g,' ').toLowerCase()).digest('hex');

export interface SocialEvent {id:string;type:string;actorId:string|null;targetId:string|null;summary:string;importance:number;privacy:string;dueAt:string|null;consumedAt:string|null;metadata:Record<string,unknown>;createdAt:string;}
export interface ActorState {actorId:string;mood:string;energy:number;focus:string;currentActivity:string;lastPostAt:string|null;lastInteractionAt:string|null;updatedAt:string;}

export class SocialStore {
  constructor(private readonly store:SorenDatabase){}
  ensureActors(actors:SocialActor[]){const statement=this.store.db.prepare(`INSERT INTO social_actors (id,kind,nickname,avatar,personality,relation_to_soren,relation_to_user,memory_json,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,nickname=excluded.nickname,avatar=excluded.avatar,personality=excluded.personality,relation_to_soren=excluded.relation_to_soren,relation_to_user=excluded.relation_to_user,active=excluded.active,updated_at=excluded.updated_at`),state=this.store.db.prepare(`INSERT OR IGNORE INTO social_actor_state (actor_id,mood,energy,focus,current_activity,updated_at) VALUES (?,?,?,?,?,?)`),at=now();this.store.db.transaction(()=>{for(const actor of actors){statement.run(actor.id,actor.kind,actor.nickname,actor.avatar,actor.personality,actor.relationToSoren,actor.relationToUser,JSON.stringify(actor.memory),actor.active?1:0,at,at);state.run(actor.id,'平静',60,actor.id==='soren'?'代码、阅读和自己的生活':'自己的日常','',at);}})();}
  reconcileRecentUserPosts(){const cutoff=new Date(Date.now()-24*60*60_000).toISOString(),rows=this.store.db.prepare(`SELECT id,content FROM moments WHERE author_id='user' AND deleted_at IS NULL AND created_at>=? AND NOT EXISTS (SELECT 1 FROM social_events WHERE type='user_post' AND target_id=moments.id)`).all(cutoff) as Array<{id:string;content:string}>;for(const row of rows){const dueAt=new Date(Date.now()+30_000+Math.random()*90_000).toISOString();this.addEvent({type:'user_post',actorId:'soren',targetId:row.id,summary:`用户发布了一条朋友圈：${row.content.slice(0,500)}`,importance:8,dueAt,metadata:{momentId:row.id,reconciled:true}});this.nudgeEvaluation(dueAt);}return rows.length;}
  reconcileRecentUserReplies(){const cutoff=new Date(Date.now()-24*60*60_000).toISOString(),rows=this.store.db.prepare(`SELECT reply.id,reply.moment_id momentId,reply.content,target.author_id recipientId,reply.reply_to_comment_id replyToCommentId FROM moment_comments reply JOIN moment_comments target ON target.id=reply.reply_to_comment_id WHERE reply.author_id='user' AND target.author_id<>'user' AND reply.created_at>=? AND NOT EXISTS (SELECT 1 FROM social_events event WHERE event.type='user_comment' AND json_extract(event.metadata_json,'$.commentId')=reply.id)`).all(cutoff) as Array<{id:string;momentId:string;content:string;recipientId:string;replyToCommentId:string}>;for(const row of rows){const dueAt=new Date(Date.now()+30_000+Math.random()*90_000).toISOString();this.addEvent({type:'user_comment',actorId:row.recipientId,targetId:row.momentId,summary:`用户回复：${row.content.slice(0,500)}`,importance:8,dueAt,metadata:{commentId:row.id,replyToCommentId:row.replyToCommentId,reconciled:true}});this.nudgeEvaluation(dueAt);}return rows.length;}
  actors(){return(this.store.db.prepare('SELECT * FROM social_actors WHERE active=1 ORDER BY CASE kind WHEN \'user\' THEN 0 WHEN \'soren\' THEN 1 ELSE 2 END,nickname').all() as any[]).map(this.mapActor);}
  actor(id:string):SocialActor|null{const row=this.store.db.prepare('SELECT * FROM social_actors WHERE id=?').get(id) as any;return row?this.mapActor(row):null;}
  feed(limit=50,actorId=''):MomentPost[]{const safe=Math.max(1,Math.min(100,Math.floor(limit)||50)),rows=this.store.db.prepare(`SELECT * FROM moments WHERE deleted_at IS NULL AND (?='' OR author_id=?) ORDER BY created_at DESC LIMIT ?`).all(actorId,actorId,safe) as any[];if(!rows.length)return[];const ids=rows.map(row=>row.id),marks=ids.map(()=>'?').join(','),actors=new Map(this.actors().map(actor=>[actor.id,actor])),media=(this.store.db.prepare(`SELECT * FROM moment_media WHERE moment_id IN (${marks}) ORDER BY created_at`).all(...ids) as any[]).map(this.media),comments=(this.store.db.prepare(`SELECT * FROM moment_comments WHERE moment_id IN (${marks}) ORDER BY created_at`).all(...ids) as any[]).map(row=>this.comment(row,actors)),likes=(this.store.db.prepare(`SELECT * FROM moment_likes WHERE moment_id IN (${marks}) ORDER BY created_at`).all(...ids) as any[]).map(row=>this.like(row,actors));return rows.map(row=>{const authorId=row.author_id||row.author,actor=actors.get(authorId)||actors.get(row.author)||actors.get('soren')!;const postLikes=likes.filter(item=>item.momentId===row.id);return{id:row.id,author:actor.kind,authorId,actor,content:row.content,location:row.location||'',worldContext:row.world_context||'',imageDescription:row.image_description||'',readAt:row.read_at,createdAt:row.created_at,updatedAt:row.updated_at,media:media.filter(item=>item.momentId===row.id),likes:postLikes,likedByUser:postLikes.some(item=>item.actorId==='user'),comments:comments.filter(item=>item.momentId===row.id)};});}
  post(id:string){return this.feed(100).find(item=>item.id===id)||null;}
  createPost(actorId:string,input:{content:string;location?:string;worldContext?:string;imageDescription?:string;motivation?:string;sourceEventId?:string|null;createdAt?:string}){const actor=this.actor(actorId);if(!actor)throw new Error('发布者不存在');const content=input.content.trim(),image=(input.imageDescription||'').trim();if(!content&&!image)throw new Error('动态内容不能为空');const hash=fingerprint(`${content}\n${image}`),duplicate=this.store.db.prepare("SELECT id FROM moments WHERE author_id=? AND fingerprint=? AND created_at>=datetime('now','-30 days') LIMIT 1").get(actorId,hash) as any;if(duplicate)throw new Error('这条动态最近已经发过');const id=crypto.randomUUID(),at=input.createdAt||now(),readAt=actor.kind==='user'?at:null;this.store.db.prepare(`INSERT INTO moments (id,author,content,location,world_context,read_at,created_at,updated_at,author_id,image_description,motivation,source_event_id,fingerprint) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,actor.kind,content,(input.location||'').trim(),(input.worldContext||'').trim(),readAt,at,at,actorId,image,(input.motivation||'').trim(),input.sourceEventId||null,hash);this.store.db.prepare('UPDATE social_actor_state SET last_post_at=?,updated_at=? WHERE actor_id=?').run(at,at,actorId);return this.post(id)!;}
  deletePost(id:string,requesterId:string){const row=this.store.db.prepare('SELECT author_id FROM moments WHERE id=? AND deleted_at IS NULL').get(id) as any;if(!row)return false;if(requesterId!=='user'&&row.author_id!==requesterId)return false;if(requesterId==='user'&&row.author_id!=='user')return false;this.store.db.prepare('UPDATE moments SET deleted_at=?,updated_at=? WHERE id=?').run(now(),now(),id);return true;}
  systemDeleteOwnPost(id:string,actorId:string){const result=this.store.db.prepare('UPDATE moments SET deleted_at=?,updated_at=? WHERE id=? AND author_id=? AND deleted_at IS NULL').run(now(),now(),id,actorId);return result.changes>0;}
  addComment(momentId:string,actorId:string,content:string,replyToCommentId:string|null=null){const actor=this.actor(actorId);if(!actor||!this.store.db.prepare('SELECT id FROM moments WHERE id=? AND deleted_at IS NULL').get(momentId))return null;const count=Number((this.store.db.prepare('SELECT COUNT(*) count FROM moment_comments WHERE moment_id=?').get(momentId) as any).count);if(actorId!=='user'&&count>=12)return null;if(replyToCommentId&&!this.store.db.prepare('SELECT id FROM moment_comments WHERE id=? AND moment_id=?').get(replyToCommentId,momentId))return null;const id=crypto.randomUUID(),at=now();this.store.db.prepare('INSERT INTO moment_comments (id,moment_id,author,content,reply_to_comment_id,created_at,author_id) VALUES (?,?,?,?,?,?,?)').run(id,momentId,actor.kind,content.trim(),replyToCommentId,at,actorId);this.store.db.prepare('UPDATE social_actor_state SET last_interaction_at=?,updated_at=? WHERE actor_id=?').run(at,at,actorId);return this.comment(this.store.db.prepare('SELECT * FROM moment_comments WHERE id=?').get(id),new Map(this.actors().map(item=>[item.id,item])));}
  toggleLike(momentId:string,actorId:string){const existing=this.store.db.prepare('SELECT id FROM moment_likes WHERE moment_id=? AND actor_id=?').get(momentId,actorId) as any;if(existing){this.store.db.prepare('DELETE FROM moment_likes WHERE id=?').run(existing.id);return false;}if(!this.actor(actorId)||!this.store.db.prepare('SELECT id FROM moments WHERE id=? AND deleted_at IS NULL').get(momentId))throw new Error('动态不存在');this.store.db.prepare('INSERT INTO moment_likes VALUES (?,?,?,?)').run(crypto.randomUUID(),momentId,actorId,now());return true;}
  unreadCount(){return Number((this.store.db.prepare("SELECT COUNT(*) count FROM moments WHERE author_id<>'user' AND read_at IS NULL AND deleted_at IS NULL").get() as any).count);}
  markRead(ids:string[]=[]){const at=now();if(ids.length){const marks=ids.map(()=>'?').join(',');this.store.db.prepare(`UPDATE moments SET read_at=? WHERE author_id<>'user' AND read_at IS NULL AND id IN (${marks})`).run(at,...ids);}else this.store.db.prepare("UPDATE moments SET read_at=? WHERE author_id<>'user' AND read_at IS NULL AND deleted_at IS NULL").run(at);return this.unreadCount();}
  addEvent(input:{type:string;actorId?:string|null;targetId?:string|null;summary:string;importance?:number;privacy?:string;dueAt?:string|null;metadata?:Record<string,unknown>}){const id=crypto.randomUUID(),at=now();this.store.db.prepare('INSERT INTO social_events VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,input.type,input.actorId||null,input.targetId||null,input.summary.trim().slice(0,2000),Math.max(1,Math.min(10,input.importance||5)),input.privacy||'private',input.dueAt||null,null,JSON.stringify(input.metadata||{}),at);this.pruneEvents();return this.event(this.store.db.prepare('SELECT * FROM social_events WHERE id=?').get(id));}
  nudgeEvaluation(dueAt:string){const current=this.store.setting<string>('momentsNextEvaluationAt','');if(!current||Date.parse(dueAt)<Date.parse(current))this.store.setSetting('momentsNextEvaluationAt',dueAt);}
  pendingEvents(limit=20,at=now()){return(this.store.db.prepare("SELECT * FROM social_events WHERE consumed_at IS NULL AND (due_at IS NULL OR due_at<=?) ORDER BY importance DESC,created_at LIMIT ?").all(at,limit) as any[]).map(this.event);}
  consumeEvents(ids:string[]){if(!ids.length)return;const marks=ids.map(()=>'?').join(',');this.store.db.prepare(`UPDATE social_events SET consumed_at=? WHERE id IN (${marks})`).run(now(),...ids);}
  state(actorId:string):ActorState{const row=this.store.db.prepare('SELECT * FROM social_actor_state WHERE actor_id=?').get(actorId) as any;return this.actorState(row);}
  updateState(actorId:string,patch:Partial<Pick<ActorState,'mood'|'energy'|'focus'|'currentActivity'|'lastInteractionAt'>>){const current=this.state(actorId),next={...current,...patch},at=now();this.store.db.prepare('UPDATE social_actor_state SET mood=?,energy=?,focus=?,current_activity=?,last_interaction_at=?,updated_at=? WHERE actor_id=?').run(next.mood,Math.max(0,Math.min(100,Number(next.energy)||0)),next.focus,next.currentActivity,next.lastInteractionAt,at,actorId);return this.state(actorId);}
  appendMemory(actorId:string,memory:string){const actor=this.actor(actorId);if(!actor||!memory.trim())return;const items=[...actor.memory,memory.trim().slice(0,300)].slice(-20);this.store.db.prepare('UPDATE social_actors SET memory_json=?,updated_at=? WHERE id=?').run(JSON.stringify(items),now(),actorId);}
  generatedToday(){const start=new Date();start.setHours(0,0,0,0);return Number((this.store.db.prepare("SELECT COUNT(*) count FROM moments WHERE motivation<>'' AND motivation<>'manual' AND created_at>=?").get(start.toISOString()) as any).count);}
  generatedInteractionsToday(){const start=new Date();start.setHours(0,0,0,0);return Number((this.store.db.prepare("SELECT COUNT(*) count FROM moment_comments WHERE author_id<>'user' AND created_at>=?").get(start.toISOString()) as any).count);}
  recentActivity(limit=30){const posts=this.feed(Math.min(limit,20)).map(item=>({type:'post',at:item.createdAt,actorId:item.authorId,text:item.content||item.imageDescription}));const comments=(this.store.db.prepare('SELECT author_id,content,created_at FROM moment_comments ORDER BY created_at DESC LIMIT ?').all(limit) as any[]).map(row=>({type:'comment',at:row.created_at,actorId:row.author_id,text:row.content}));return[...posts,...comments].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).slice(0,limit);}
  private pruneEvents(){this.store.db.prepare("DELETE FROM social_events WHERE consumed_at IS NOT NULL AND created_at<datetime('now','-30 days')").run();}
  private mapActor=(row:any):SocialActor=>({id:row.id,kind:row.kind,nickname:row.nickname,avatar:row.avatar,personality:row.personality,relationToSoren:row.relation_to_soren,relationToUser:row.relation_to_user,memory:parse<string[]>(row.memory_json,[]),active:bool(row.active)});
  private media=(row:any):MomentMedia=>({id:row.id,momentId:row.moment_id,kind:row.kind,path:row.path,mime:row.mime,size:Number(row.size),createdAt:row.created_at});
  private comment=(row:any,actors:Map<string,SocialActor>):MomentComment=>{const actor=actors.get(row.author_id||row.author)||actors.get('soren')!;return{id:row.id,momentId:row.moment_id,author:actor.kind,authorId:actor.id,actor,content:row.content,replyToCommentId:row.reply_to_comment_id,createdAt:row.created_at};};
  private like=(row:any,actors:Map<string,SocialActor>):MomentLike=>({id:row.id,momentId:row.moment_id,actorId:row.actor_id,actor:actors.get(row.actor_id)!,createdAt:row.created_at});
  private event=(row:any):SocialEvent=>({id:row.id,type:row.type,actorId:row.actor_id,targetId:row.target_id,summary:row.summary,importance:Number(row.importance),privacy:row.privacy,dueAt:row.due_at,consumedAt:row.consumed_at,metadata:parse(row.metadata_json,{}),createdAt:row.created_at});
  private actorState=(row:any):ActorState=>({actorId:row.actor_id,mood:row.mood,energy:Number(row.energy),focus:row.focus,currentActivity:row.current_activity,lastPostAt:row.last_post_at,lastInteractionAt:row.last_interaction_at,updatedAt:row.updated_at});
}

