import type { SocialActor,SorenSelfState } from '@soren/shared';
import type { CodexRuntime } from '@soren/runtime-codex';
import type { SorenDatabase } from './db.js';
import type { SorenIdentitySource } from './persona-service.js';
import type { ActorState,SocialEvent } from './social-store.js';

export interface SocialInteractionDecision{type:'like'|'comment';actorId:string;targetMomentId?:string;content?:string;replyToCommentId?:string|null;}
export interface SocialGenerationDecision{action:'none'|'post'|'interact'|'delete';reason:string;content?:string;imageDescription?:string;location?:string;targetMomentId?:string;replyToCommentId?:string|null;interactions?:SocialInteractionDecision[];statePatch?:Partial<Pick<ActorState,'mood'|'energy'|'focus'|'currentActivity'>>;memory?:string;}
export interface SocialGenerationRequest{now:string;actor:SocialActor;actors:SocialActor[];state:ActorState;selfState?:SorenSelfState;events:SocialEvent[];recentChats:Array<{role:string;content:string;createdAt:string}>;recentPosts:Array<{id:string;authorId:string;author:string;content:string;imageDescription:string;createdAt:string;comments:Array<{id:string;authorId:string;content:string}>}>;recentActivity:Array<{type:string;at:string;actorId:string;text:string}>;}
export interface SocialGenerator{generate(request:SocialGenerationRequest):Promise<SocialGenerationDecision>;}

function parseDecision(text:string):SocialGenerationDecision{const fenced=text.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1],object=fenced||text.slice(text.indexOf('{'),text.lastIndexOf('}')+1),parsed=JSON.parse(object);if(!['none','post','interact','delete'].includes(parsed.action))throw new Error('生活生成器返回了未知动作');return parsed;}

export async function buildSocialPrompt(request:SocialGenerationRequest,identity:SorenIdentitySource){const safe={...request,actor:{...request.actor,personality:request.actor.id==='soren'?'由统一 Soren Core 提供':request.actor.personality},actors:request.actors.map(actor=>({...actor,personality:actor.id==='soren'?'由统一 Soren Core 提供':actor.personality,memory:actor.memory.slice(-8)})),events:request.events.slice(0,12),recentChats:request.recentChats.slice(0,12),recentPosts:request.recentPosts.slice(0,12),recentActivity:request.recentActivity.slice(0,20)},actorIdentity=request.actor.id==='soren'?await identity.scene('你正在根据持续的数字生活状态与近期事件，决定是否在私人朋友圈采取一次行动。场景指令只能约束本次动作，不能改变你的身份。'):`=== Social Actor Identity ===\n昵称：${request.actor.nickname}\n人格：${request.actor.personality}\n与 Soren 的关系：${request.actor.relationToSoren}\n与用户的关系：${request.actor.relationToUser}`;return`${actorIdentity}\n\n=== SocialLife Scene Contract ===\n你只替当前 actor 做一次生活决策，不写客服回复，不总结日志。必须只返回一个 JSON 对象，不要 Markdown。结构：\n{"action":"none|post|interact|delete","reason":"简短内部原因","content":"可选","imageDescription":"可选的生活照片画面描述，不要写AI提示词","location":"可选","targetMomentId":"互动或删除目标","replyToCommentId":"可选","interactions":[{"type":"like|comment","actorId":"固定角色ID","targetMomentId":"可选，默认新动态","content":"评论时必填","replyToCommentId":"可选"}],"statePatch":{"mood":"","energy":0,"focus":"","currentActivity":""},"memory":"可选的简短互动记忆"}\n\n规则：\n- 不调用工具，不读写文件；唯一任务是返回 JSON。\n- 先判断是否真有公开表达动机；没有就 action=none。\n- 不复制私人聊天原文，不机械同步，不把恋爱当作全部。\n- Soren 的身份与表达完全服从上面的 Soren Core；NPC 严格遵循各自固定人格。\n- 允许短句或仅图片描述，避免作文、总结腔、连续煽情和模板句式。\n- interact 用于回应评论或参与朋友动态，评论不超过 3 条。\n- delete 只能删除 actor 自己的旧动态，并且应当罕见。\n- recentPosts 已有相似表达时必须 none 或使用真正不同的事件。\n\n当前上下文：\n${JSON.stringify(safe)}`;}

export class CodexSocialGenerator implements SocialGenerator{
  constructor(private readonly runtime:CodexRuntime,private readonly db:SorenDatabase,private readonly cwd:string,private readonly identity:SorenIdentitySource){}
  async generate(request:SocialGenerationRequest){let threadId=this.db.setting<string>('momentsLifeThreadId','');if(!threadId){threadId=await this.runtime.createThread(this.cwd,'');this.db.setSetting('momentsLifeThreadId',threadId);}let text='';try{const result=await this.runtime.run({threadId,cwd:this.cwd,effort:'low',onEvent:event=>{if(event.type==='delta')text+=event.text;},text:await buildSocialPrompt(request,this.identity)});return parseDecision(text||result.text);}catch(error){this.db.setSetting('momentsLifeThreadId','');throw error;}}
}
